### ISSUE TITLE
vpnc dependency kernel-module-tun

### ISSUE THREAD

**Issue by SunMar** [Optware/Optware-ng#102]
When I try to install the vpnc package I get the error:
`ERROR: Cannot satisfy the following dependencies for vpnc:
         kernel-module-tun`

However there is no kernel-module-tun package to install. The installed kernel does include the tun module compiled so I don't need that package anyway (Synology DS215+ with DSM 6).

I've solved the issue by installing vpnc with -nodeps and the package works great. I'm reporting it because I'm unsure whether this is intended or an omission/bug with the dependencies.

**Comment by alllexx88** [comment]
Thank you for the report! This is indeed a bug, probably left from the old days when Optware had nslu2 feed only, and did have kernel module packages.

**Comment by alllexx88** [comment]
Fixed in d4fe813878466daa4bdb7cf716d300a57861e808
