### ISSUE TITLE
request for Perl module XML::Simple

### ISSUE THREAD

**Issue by GUHU0433** [Optware/Optware-ng#104]
Unfortunately, I need this perl module. Since some components must be compiled, I can not make it by myself.
It would be great to get it as an package.
Thanks in advance

**Comment by alllexx88** [comment]
I've added this module (`perl-libxml-simple` package) together with some missing dependencies, but I discovered that nothing had to be compiled actually (except the already previously provided perl-libxml package). Ubuntu states the same: http://packages.ubuntu.com/wily/libxml-simple-perl

**Comment by GUHU0433** [comment]
Thanks a lot. I got the sources from CPAN. It said there are depencies, one has told me to compile sth,
Great!

**Comment by alllexx88** [comment]
@GUHU0433 It turns out that `perl-libxml-libxml` and `perl-libxml` are different packages, and I had to add new `perl-libxml-libxml` package, which indeed has libxml2 bindings that had to be compiled, so you were right after all
