### ISSUE TITLE
/opt/bin/*: error while loading shared libraries: /opt/lib/lib*.so: internal error

### ISSUE THREAD

**Issue by cswl** [Optware/Optware-ng#105]
0After an ipkg update and upgrade today  (a rch is armv7hf ). 
 I'm getting the above errors while running some binaries.
 I tried with `file` `ssh` `ls` and others. They all give error as above, saying error while loading shared libraries internal error.

The libraries seem to be there and read, from strace output for `ls`.

```
open("/opt/lib/libcap.so.2", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0T\17\0\0004\0\0\0l6\0\0\2\4\0\0054\0 \0\4\0(\0\30\0\27\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0x1\0\0x1\0\0\5\0\0\0\0\0\1\0\1\0\0\0x1\0\0x1\1\0x1\1\0\360\3\0\0\364\3\0\0\6\0\0\0\0\0\1\0\2\0\0\0D3\0\0D3\1\0D3\1\0\360\0\0\0\360\0\0\0\6\0\0\0\4\0\0\0Q\345td\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\6\0\0\0\20\0\0\0%\0\0\0E\0\0\0/\0\0\0008\0\0\0\33\0\0\0=\0\0\0)\0\0\0\0\0\0\0D\0\0\0\0\0\0\0005\0\0\0007\0\0\0\0\0\0\0\0\0\0\0;\0\0\0\0\0\0\0C\0\0\0<\0\0\0\34\0\0\0*\0\0\0\21\0\0\0@\0\0\0001\0\0\0\10\0\0\0\0\0\0\0\"\0\0\0\0\0\0\0\32\0\0\0\31\0\0\0?\0\0\0\37\0\0\0&\0\0\0006\0\0\0003\0\0\0B\0\0\0>\0\0\0000\0\0\0002\0\0\0\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\4\0\0\0\0\0\0\0\0\0\0\0\7\0\0\0\0\0\0\0\t\0\0\0\0\0\0\0\0\0\0\0\16\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\r\0\0\0\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\24\0\0\0\17\0\0\0\27\0\0\0\v\0\0\0\f\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0 \0\0\0\30\0\0\0\n\0\0\0\35\0\0\0\23\0\0\0\0\0\0\0\36\0\0\0\0\0\0\0%\0\0\0\0\0\0\0", 512) = 512
close(4)                                = 0
writev(2, [{"/opt/bin/ls", 11}, {": ", 2}, {"error while loading shared libraries", 36}, {": ", 2}, {"/opt/lib/libcap.so.2", 20}, {": ", 2}, {"internal error", 14}, {"", 0}, {"", 0}, {"\n", 1}], 10/opt/bin/ls: error while loading shared libraries: /opt/lib/libcap.so.2: internal error
) = 88
exit_group(127)                         = ?
+++ exited with 127 +++
```

**Comment by alllexx88** [comment]
Hmm, too bad I don't currently have armv7hf device to test. I recently upgraded toolchains, and this change didn't break anything, as far as I can tell, for i686:

```
DiskStation> /opt/bin/ls
conffiles                               data.tar.gz                             deluge-develop_20150223-4_i686.ipk      optware
control                                 debian-binary                           log.txt
control.tar.gz                          deluge-develop-gtk_20150223-4_i686.ipk  minify_web_js.py
DiskStation> /opt/bin/file
Usage: file [-bcEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type]
            [-e testname] [-F separator] [-f namefile] [-m magicfiles] file ...
       file -C [-m magicfiles]
       file [--help]
DiskStation> /opt/bin/ssh
Dropbear SSH client v2015.68 https://matt.ucc.asn.au/dropbear/dropbear.html
Usage: /opt/bin/ssh [options] [user@]host[/port][,[user@]host/port],...] [command]
-p <remoteport>
-l <username>
-t    Allocate a pty
-T    Don't allocate a pty
-N    Don't run a remote command
-f    Run in background after auth
-y    Always accept remote host key if unknown
-y -y Don't perform any remote host key checking (caution)
-s    Request a subsystem (use by external sftp)
-i <identityfile>   (multiple allowed, default .ssh/id_dropbear)
-A    Enable agent auth forwarding
-L <[listenaddress:]listenport:remotehost:remoteport> Local port forwarding
-g    Allow remote hosts to connect to forwarded ports
-R <[listenaddress:]listenport:remotehost:remoteport> Remote port forwarding
-W <receive_window_buffer> (default 24576, larger may be faster, max 1MB)
-K <keepalive>  (0 is never, default 0)
-I <idle_timeout>  (0 is never, default 0)
-B <endhost:endport> Netcat-alike forwarding
-J <proxy_program> Use program pipe rather than TCP connection
-c <cipher list> Specify preferred ciphers ('-c help' to list options)
-m <MAC list> Specify preferred MACs for packet verification (or '-m help')
-V    Version
```

Other archs I tested seem to be fine too. Could you please try to manually downgrade glibc to previous version?

```
#comment out feed source:
sed -i -e '/^src\/gz/s/^/#/' /opt/etc/ipkg.conf
ipkg update
ipkg remove -force-depends glibc-opt libnsl
ipkg install http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabihf/libnsl_2.21-1_arm.ipk http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabihf/glibc-opt_2.21-2_arm.ipk
```
(to uncomment the feed source later on: `sed -i -e '/^#src\/gz/s/#//' /opt/etc/ipkg.conf`)

If this cures the problem, I'll trigger a full feed rebuild with the new toolchain, and after it's done, issues should be fixed by reinstalling all installed packages.

**Comment by cswl** [comment]
I noticed, that all of the binaries that were erroring out are all dynamically linked ones. Not just the ones I listed..  

After downgrading glibc all of them are working again...

I think, the error is coming from http://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-load.c#l1662, 
As the strace output, the file is opened and the headers are read...  
So maybe some ELF breakage..

**Comment by alllexx88** [comment]
Buildroot 2016.02 introduces some new patches to glibc 2.21. Maybe, some of them break backward compatibility for this platform. I've triggered a full feed rebuild, you can check its progress [here](http://jenkins.nas-admin.org/view/Optware). After the feed is built, indexed and rsync'ed (check the jenkins page, or wait till I let you know of it), reinstall all installed packages with `ipkg update; ipkg -force-reinstall install $(ipkg list_installed|cut -d ' ' -f1)` -- this should hopefully fix the issue.

**Comment by alllexx88** [comment]
Ah, I found mistake in Buildroot arch-related config. They made some changes to the code, so oldconfig didn't work properly this time. I had to make some adjustments manually, which I would've notice if I had a testing machine, but this isn't hard to fix -- too bad I've cleaned the built feed already :D anyway, when it's fixed, built and uploaded, you'll only need `ipkg update; ipkg upgrade`

**Comment by alllexx88** [comment]
@cswl should be fixed now: run `ipkg update; ipkg upgrade`

**Comment by cswl** [comment]
@allexx88 Alright, only glibc-opt and libnsl got upgraded...  and everythings working again.
Thanks..  I guess this can be closed now..

**Comment by alllexx88** [comment]
Great! Thank you for reporting
