### ISSUE TITLE
compiling for mipsel. gnutls errors.

### ISSUE THREAD

**Issue by kokotonix** [Optware/Optware-ng#108]
git cloned some 2h ago.

I'm trying to compile optware-ng for mipsel.
configure makefile for 
OPTWARE_TARGET ?= buildroot-mipsel-ng

after " make", all was going ok until an error compiling gnutls
where several modules complains about 
 <autoopts/options.h> not being found.

Meanwhile, I've disabled gnutls compilation in the main makefile, but I'm not sure the implications it'll mean in the end ...

**Comment by kokotonix** [comment]
nope... even removing gnutls from the makefile, it tries to compile-it.

By the way, the error is:

CC       srptool-args.lo
In file included from srptool-args.c:43:0:
srptool-args.h:49:30: fatal error: autoopts/options.h: No such file or directory
compilation terminated.

**Comment by alllexx88** [comment]
Hi,
You're doing it the wrong way: you shouldn't edit the Makefile and try to compile in the root Optware-ng dir. You should configure target dir(s): see https://github.com/Optware/Optware-ng/wiki/Contributing-to-Optware-ng

**Comment by kokotonix** [comment]
yeah. you're right.
Done as suggested in the link.

As a reference, this is what I've done for mipsel:
make buildroot-mipsel-ng-target
cd buildroot-mipsel-ng
make directories toolchain ipkg-utils
make 

It compiled just nice.
(I have other questions, but this issue is closed)

thanks :)
