### ISSUE TITLE
"Only have 0 available blocks on filesystem /"

### ISSUE THREAD

**Issue by ElTopo** [Optware/Optware-ng#109]
I recently saw this issue when I tried to install / upgrade some packages, for example, when I did "ipkg upgrade", I got 

Collected errors:
Only have 0 available blocks on filesystem /, pkg gettext needs 20376
Only have 0 available blocks on filesystem /, pkg gettext needs 20376

Indeed my / is 100% full, but packages are supposed to be installed in /opt, which has plenty free space:

 $ df -h
```
Filesystem                Size      Used Available Use% Mounted on
/dev/root                20.5M     20.5M         0 100% /
tmpfs                   117.0M    592.0K    116.4M   0% /tmp
devfs                   117.0M         0    117.0M   0% /dev
/dev/mtdblock5           32.0M      1.1M     30.9M   3% /jffs
/dev/sda1                29.2G      1.9G     25.8G   7% /tmp/mnt/anon32gb
```

/opt is pointing to /tmp/mnt/anon32gb/optware-ng/

my ipkg.conf:

$ cat /opt/etc/ipkg.conf
```
src/gz alllexx http://ipkg.nslu2-linux.org/optware-ng/buildroot-mipsel-ng
dest /opt/
```

How can I fix this issue?
Thanks

**Comment by alllexx88** [comment]
Hi

Simply rerun the bootstrap script: see first "Attention" section of the README for details.

Regards

**Comment by ElTopo** [comment]
@alllexx88 Thanks for the reply, issue resolved.
