### ISSUE TITLE
libc.so.1: cannot handle TLS data

### ISSUE THREAD

**Issue by LSchuepbach** [Optware/Optware-ng#112]
Hi,

I am using a MBWE Whitelight, so uname -a:
Linux Juke 2.6.24.4 #1 Thu Apr 1 16:43:58 CST 2010 armv5tejl unknown

I was using ipkg and optware for a long time without issue (http://ipkg.nslu2-linux.org/feeds/optware/cs05q1armel/cross/unstable)

After moving to armv5eabi-ng-legacy with your bootstrap script, lots of package are getting issues and lots of things are broken. Most often, for instance while trying to load "less" I get:
sort: error while loading shared libraries: libc.so.1: cannot handle TLS data

To be sure, I don't have libc.so.1 in /lib but only in /opt/lib

I've got lost on google trying to understand what I did wrong.

Let me know if you need more info (PATH, package list_installed,...) to help diagnose.

Thanks a lot

**Comment by alllexx88** [comment]
Hi,

Do you have `LD_LIBRARY_PATH` env variable set? It should be empty to not mix firmware and Optware-ng libraries. Try to unset te and see if it helps:

```
export LD_LIBRARY_PATH=
```

It's been reported [here](https://github.com/Optware/Optware-ng/issues/107) that Optware-ng works on Whitelight, but I don't owe it myself to test properly, unfotunately.

**Comment by LSchuepbach** [comment]
Thanks for the fast answer. I've added this variable to the environment, without any change.

**Comment by alllexx88** [comment]
I can't reproduce this on my armv7 router:

```
[root@unknown /opt]$ wget -O - http://ipkg.nslu2-linux.org/optware-ng/bootstrap/buildroot-armv5eabi-ng-legacy-bootstrap.sh | sh
...
Bootstraping done
[root@unknown /opt]$ ipkg update
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/Packages.gz.
Inflating http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/Packages.gz.
Updated list of available packages in /opt/lib/ipkg/lists/alllexx.
[root@unknown /opt]$ ipkg install less
Installing less (444-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/less_444-1_arm.ipk.
Installing uclibc-opt (1.0.13-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/uclibc-opt_1.0.13-1_arm.ipk.
Installing ncursesw (5.7-2) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/ncursesw_5.7-2_arm.ipk.
Installing ncurses (5.7-4) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/ncurses_5.7-4_arm.ipk.
Configuring uclibc-opt.
Configuring ncurses.
update-alternatives: Linking //opt/bin/clear to /opt/bin/ncurses-clear
Configuring ncursesw.
Configuring less.
update-alternatives: Linking //opt/bin/less to /opt/bin/less-less
[root@unknown /opt]$ /opt/bin/less
Missing filename ("less --help" for help)
```

As you can see, `less` is working. And so do other things I tried (`mc`, `nano` etc.).

This `cannot handle TLS data` error means that Optware-ng binaries pick up some firmware shared libraries (that are probably built without Thread Local Storage (TLS) support) for some reason. What's the output of `strace /opt/bin/less` (if `less` fails on you with the error above)?

**Comment by alllexx88** [comment]
And more "heavy" things work as well, like BubbleUPnP Server using OpenJDK7.

I'm not sure what else apart from wrong arch, `LD_LIBRARY_PATH` env variable and old kernel (2.6.24.4 should be OK for `buildroot-armv5eabi-ng-legacy`, which was built with 2.6.22 kernel headers) can break Optware-ng on Linux platforms.

**Comment by LSchuepbach** [comment]
Still puzzle me as well. To be sure it would not be problem due to the mix of optware and new stuff, I've erased the whole optware for a clean version. Still have the problem.

```bash
~ # rm -r /opt
~ # less backup.log
-sh: less: not found
~ # wget -O - http://ipkg.nslu2-linux.org/optware-ng/bootstrap/buildroot-armv5eabi-ng-legacy-bootstrap.sh | sh
[...]
./data.tar.gz
./
./opt/
./opt/bin/
./opt/bin/ipkg-static
./opt/bin/ipkg
./opt/bin/update-alternatives
./opt/var/
./opt/var/lock/
./opt/share/
./opt/share/man/
./opt/share/man/man1/
./opt/share/man/man1/opkg-cl.1
./opt/share/opkg/
./opt/share/opkg/intercept/
./opt/share/opkg/intercept/update-modules
./opt/share/opkg/intercept/depmod
./opt/share/opkg/intercept/ldconfig
./opt/etc/
./opt/etc/ipkg/
./opt/etc/ipkg/ipkg.conf
./opt/etc/ipkg.conf
Bootstraping done
~ # ipkg update
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/Packages.gz.
Inflating http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/Packages.gz.
Updated list of available packages in /opt/lib/ipkg/lists/alllexx.
~ # ipkg install less
Installing less (444-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/less_444-1_arm.ipk.
Installing uclibc-opt (1.0.13-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/uclibc-opt_1.0.13-1_arm.ipk.
Installing ncursesw (5.7-2) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/ncursesw_5.7-2_arm.ipk.
Installing ncurses (5.7-4) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/ncurses_5.7-4_arm.ipk.
Configuring uclibc-opt.
Configuring ncurses.
sort: error while loading shared libraries: libc.so.1: cannot handle TLS data
update-alternatives: removing //opt/bin/clear as no more alternatives exist for it
Configuring ncursesw.
Configuring less.
sort: error while loading shared libraries: libc.so.1: cannot handle TLS data
update-alternatives: removing //opt/bin/less as no more alternatives exist for it
~ # ipkg list_installed
less - 444-1
ncurses - 5.7-4
ncursesw - 5.7-2
uclibc-opt - 1.0.13-1
~ # less backup.log
-sh: less: not found
~ # ls /opt/lib/
ipkg                    libm-1.0.13.so          libpanelw.so
ld-uClibc-1.0.13.so     libm.so.1               libpanelw.so.5
ld-uClibc.so.0          libmenu.so              libpanelw.so.5.7
ld-uClibc.so.1          libmenu.so.5            libpthread-1.0.13.so
libc.so.1               libmenu.so.5.7          libpthread.so.1
libcrypt-1.0.13.so      libmenuw.so             libresolv-1.0.13.so
libcrypt.so.1           libmenuw.so.5           libresolv.so.1
libdl-1.0.13.so         libmenuw.so.5.7         librt-1.0.13.so
libdl.so.1              libncurses.so           librt.so.1
libform.so              libncurses.so.5         libthread_db-1.0.13.so
libform.so.5            libncurses.so.5.7       libthread_db.so.1
libform.so.5.7          libncursesw.so          libuClibc-1.0.13.so
libformw.so             libncursesw.so.5        libutil-1.0.13.so
libformw.so.5           libncursesw.so.5.7      libutil.so.1
libformw.so.5.7         libpanel.so             terminfo
libgcc_s.so             libpanel.so.5
libgcc_s.so.1           libpanel.so.5.7
```

**Comment by LSchuepbach** [comment]
Having a clean /opt helps to see more easily what's there and what's not. In `/opt/bin` I don't have `less` but `less-less`, which works as expected. So, my guess is that something's wrong somewhere in some post-installation script, but I have to admit I have no clue how that works.

**Comment by alllexx88** [comment]
@LSchuepbach It's clear from your log that it's *firmware* binaries that are failing:

```
Configuring ncurses.
sort: error while loading shared libraries: libc.so.1: cannot handle TLS data
update-alternatives: removing //opt/bin/clear as no more alternatives exist for it
```
and
```
Configuring less.
sort: error while loading shared libraries: libc.so.1: cannot handle TLS data
update-alternatives: removing //opt/bin/less as no more alternatives exist for it
```
These lines show that calls to firmware `sort` by Optware-ng `update-alternatives` shell script fail, thus not linking `/opt/bin/clear` and `/opt/bin/less` to `/opt/bin/ncurses-clear` and `/opt/bin/less-less`, respectively. I see two possible reasons for this:

* you do have `LD_LIBRARY_PATH` set, despite of what you said. Please double-check with `echo ${LD_LIBRARY_PATH}`
* you have some libs in `/opt/lib` indexed by `ldconfig`, which are picked up in favor of firmware ones. If you have `ldconfig` on your firmware, make sure that `/etc/ld.so.conf` doesn't have `/opt/*` lines and run `ldconfig`

**Comment by alllexx88** [comment]
Closing due to no response
