### ISSUE TITLE
bacula: not compiled with LZO?

### ISSUE THREAD

**Issue by FlorianHeigl** [Optware/Optware-ng#114]
Hi,

I'm pretty sure bacula-fd is not compiled with LZO support, which massively helps backup compression speed.
Check out this old bug from Alpine Linux for a similar case:
https://bugs.alpinelinux.org/issues/2086

I'd installed lzo and liblzma and whatever I could think of, but it's not picking up the compression.
I haven't found out where ldd is, otherwise I'd supply more info.

Basically what's needed is that lzo is installed at compile + run time or it WILL disable it.

Let me know if there's something I can do to help. I can't completely dive into optware though.

**Comment by FlorianHeigl** [comment]
I can't even find the source directory, and ipkg seems to have no --version switch.
now, i would love to tell you i'm confident i'm using the right thing.

I'll post back if i find some version :/

**Comment by alllexx88** [comment]
Hi,

LZO enabled in bacula: see b81d1721ff50e6605250cd99c157dcbcf3d86f34

It's building and will arrive to the feeds in the matter of minutes.

**Comment by FlorianHeigl** [comment]
WOW thank you!

**Comment by FlorianHeigl** [comment]
Confirm: working
New build also needs libacl but that's just even better to have.

**Comment by alllexx88** [comment]
@FlorianHeigl Thanks for the report, `libacl` dependency added.
