### ISSUE TITLE
ntp won't install

### ISSUE THREAD

**Issue by ssl-3** [Optware/Optware-ng#116]
ntp seems to depend on libpcap.so.2, but this doesn't seem to be provided anywhere.:

```
root@unknown:/opt# ipkg install ntp
Installing ntp (4.2.6.2-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/ntp_4.2.6.2-1_arm.ipk.
Configuring ntp.
/opt/bin/ntpd: can't load library 'libcap.so.2'
Collected errors:
 * pkg_run_script: package "ntp" postinst script returned status 16.
 * opkg_configure: ntp.postinst returned 16.
root@unknown:/opt# ipkg list | grep pcap
libpcap - 1.3.0-2 - PCAP Library
libpcap-dev - 1.3.0-2 - PCAP Library header files for development
pcapsipdump - 0.1.2-3 - tool for dumping SIP sessions (+RTP traffic, if available)
root@unknown:/opt#

```

**Comment by alllexx88** [comment]
It depends on libcap -- not lib**p**cap. Should be fixed now: 5d722341104efced30ae1e1a1d97d33fe870350a

**Comment by ssl-3** [comment]
You're right:  It was libcap, not libpcap.

But, still:

`
root@unknown:/tmp/home/root# ipkg remove ntp
Removing package ntp from /opt/...
root@unknown:/tmp/home/root# ipkg update
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/Packages.gz.
Inflating http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/Packages.gz.
Updated list of available packages in /opt/lib/ipkg/lists/optware-ng.
root@unknown:/tmp/home/root# ipkg install ntp
Installing ntp (4.2.6.2-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/ntp_4.2.6.2-1_arm.ipk.
Configuring ntp.
/opt/bin/ntpd: can't load library 'libcap.so.2'
Collected errors:
 * pkg_run_script: package "ntp" postinst script returned status 16.
 * opkg_configure: ntp.postinst returned 16.
root@unknown:/tmp/home/root#
`

**Comment by ssl-3** [comment]
Except if I install libcap manually:

```
root@unknown:/tmp/home/root# ipkg install libcap
Installing libcap (2.24-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/libcap_2.24-1_arm.ipk.
Installing attr (2.4.47-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/attr_2.4.47-1_arm.ipk.
Configuring attr.
Configuring libcap.
Configuring ntp.
root@unknown:/tmp/home/root# ipkg install ntp
Package ntp (4.2.6.2-1) installed in /opt/ is up to date.
root@unknown:/tmp/home/root#
```

**Comment by ssl-3** [comment]
unless this is a release-cycle thing and I should be pulling from git instead.

**Comment by alllexx88** [comment]
There was a bug in `ntp` packaging/indexing: previous version wasn't being removed, and while numerous versions per feed aren't supported, only the older version was available via ipkg. This isn't the first time I encounter this bug. Should be all good now.
