### ISSUE TITLE
Request: MinimServer / MinimWatch packages

### ISSUE THREAD

**Issue by z4r9** [Optware/Optware-ng#117]
I'd like to request packages for MinimServer and MinimWatch. I tried to install manually on a router running optware-ng arm but got the following error:

 java.lang.UnsatisfiedLinkError: /tmp/mnt/sda1/minimserver/tmp/native/libohNet.so: File not found

http://forum.minimserver.com/showthread.php?tid=3171

Thanks!

**Comment by alllexx88** [comment]
MinimServer and MinimWatch are closed source projects, so it's impossible to add it to Optware-ng.
