### ISSUE TITLE
iperf (ARMv7 EABI softfloat) gives 'h_errno' can't resolve symbol

### ISSUE THREAD

**Issue by patelhiren** [Optware/Optware-ng#120]
Using the ARMv7 EABI softfloat feed on my R7000 running DD-WRT v3.0-r29620M kongac (05/10/16).

installed iperf and trying to run it with
`perf -s -i 1`

This gives me an error 
`/opt/bin/iperf: symbol 'h_errno': can't resolve symbol`

I have python installed from the same feed source and that runs without any problems.

**Comment by alllexx88** [comment]
It looks to me that you have `LD_LIBRARY_PATH` set. This is the only possible reason for this error I can think of. 'h_errno' is defined in the libc:

```
root@unknown:/tmp/home/root# nm -D /opt/lib/libc.so.1|grep ' h_errno'
00000008 B h_errno
```

Also, it works fine for me:

```
root@unknown:/tmp/home/root# ipkg install iperf
Installing iperf (2.0.4-2) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/iperf_2.0.4-2_arm.ipk.
Configuring iperf.
root@unknown:/tmp/home/root# /opt/bin/iperf
Usage: /opt/bin/iperf [-s|-c host] [options]
Try `/opt/bin/iperf --help' for more information.
root@unknown:/tmp/home/root# /opt/bin/iperf -s -i 1
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
```

Can you try `iperf` with unset `LD_LIBRARY_PATH`?

```
LD_LIBRARY_PATH= /opt/bin/iperf -s -i 1
```

Also, do you have `ldd`?

```
ldd /opt/bin/iperf
```

To see what libs are loaded.

**Comment by patelhiren** [comment]
Just gave your suggestions a try. Running

`LD_LIBRARY_PATH= /opt/bin/iperf -s -i 1`

does work. I dont remember setting it but may be the default dd-wrt build I have installed has it always set.

`echo $LD_LIBRARY_PATH`

gives me

`/lib:/usr/lib:/jffs/lib:/jffs/usr/lib:/jffs/usr/local/lib:/mmc/lib:/mmc/usr/lib:/opt/lib:/opt/usr/lib`

Regardless I can confirm that unsetting the LD_LIBRARY_PATH does fix it. Thanks for the tip. If you agree, I think we can close this. 👍

**Comment by alllexx88** [comment]
> Running
> 
> LD_LIBRARY_PATH= /opt/bin/iperf -s -i 1
> 
> does work. I don't remember setting it but may be the default dd-wrt build I have installed has it always set.

I' almost certain that's the default dd-wrt behaviour. I think, I remember similar issues reported by dd-wrt users. It'd be good to create an Optware-ng page on the dd-wrt wiki, and to mention this issue there.

> Thanks for the tip. If you agree, I think we can close this.

You're welcome, closing the issue
