### ISSUE TITLE
Request: perl-module IO::Socket::Multicast

### ISSUE THREAD

**Issue by GUHU0433** [Optware/Optware-ng#124]
My Dear,

is it possible to get this perl module with its depencies? I'm afraid there is sth which has to be compiled.

Thank you very much in advance.

**Comment by alllexx88** [comment]
Hi, IO::Socket::Multicast indeed depends on IO::Interface, which has to be compiled. I'll look into it soon, seems to be relatively simple.

**Comment by alllexx88** [comment]
Done: 4e1f7f29e929d1df5c8b173231302ec79274f105

**Comment by GUHU0433** [comment]
Thanks a lot. Great!

**Comment by alllexx88** [comment]
OK, I tested it myself, and v1 were flawed, but v2 (5dc31244d6fbf302e1eb0e365ab2664742acf4c8) work fine
