### ISSUE TITLE
ipkg.conf issue

### ISSUE THREAD

**Issue by elRadix** [Optware/Optware-ng#127]
can you help me here, not able to update

ipkg update
Collected errors:
 * opkg_download: Failed to download http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/Packages.gz, wget returned 4.

contents of ipkg.conf
src/gz alllexx http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng
dest /opt/ /

**Comment by alllexx88** [comment]
The config looks good to me. Maybe, http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/Packages.gz is/was unavailable for some reason on your side? Can you try to fetch it manually?

Also, try to run the bootstrap script again:

```
wget -O - http://ipkg.nslu2-linux.org/optware-ng/bootstrap/buildroot-armeabi-ng-bootstrap.sh | sh
```

**Comment by alllexx88** [comment]
Closing due to no response
