### ISSUE TITLE
libgmp dependency missing ?

### ISSUE THREAD

**Issue by nsouch** [Optware/Optware-ng#132]
Hi,
libgmp dependency in ruby2.3.1-2 package seems to be missing :
Syno> ruby
ruby: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory

My obvious workaround : install libgmp manually.

Thx.

**Comment by alllexx88** [comment]
Thanks, fixed: 46a657464eb85275e30c8fa0e1ae06328f3a8282
