### ISSUE TITLE
libgcc_s.so link missing

### ISSUE THREAD

**Issue by nsouch** [Optware/Optware-ng#133]
Hi,

/opt/lib/libgcc_s.so link to /opt/lib/libgcc_s.so.1 may be missing in package gcc - 5.3.0-9 (i686)

which prevents linking with the following error (even with correct -L options) : 
/opt/lib/gcc/i686-buildroot-linux-gnu/5.3.0/../../../../i686-buildroot-linux-gnu/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status

creating the link manually fixes the problem.

**Comment by alllexx88** [comment]
Thanks for the report. `libgcc_s.so` is supposed to be a linker script, not a link. It used to be part of `glibc-opt` package, but is gone since glibc prefix change (the files are located in a bit different locations in the toolchain after the change). I think this file is due to be present in `libc-dev` package: I'll fix it a bit later.

**Comment by nsouch** [comment]
I don't know if this helps but on my freshly (today) installed system : 
<code>Syno> ipkg files libc-dev|grep libgcc</code>
/opt/lib/libgcc.a
<code>Syno> ipkg files glibc-opt|grep libgcc</code>
/opt/lib/libgcc_s.so.1

**Comment by alllexx88** [comment]
Yeah, I know it's missing from both glibc-opt and libc-dev. It's easy to
fix, and I'll do it as soon as I get home

Пт, 24 черв. 2016 16:51 користувач nsouch <notifications@github.com> пише:

**Comment by alllexx88** [comment]
Should be fine now:

```
root@DiskStation:~# ipkg update
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-i686/Packages.gz.
Inflating http://ipkg.nslu2-linux.org/optware-ng/buildroot-i686/Packages.gz.
Updated list of available packages in /opt/lib/ipkg/lists/alllexx.
root@DiskStation:~# ipkg upgrade
Upgrading libc-dev from 2.21-2 to 2.21-3 on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-i686/libc-dev_2.21-3_i686.ipk.
Configuring libc-dev.
root@DiskStation:~# cat /opt/lib/libgcc_s.so
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library.  */
GROUP ( libgcc_s.so.1 -lgcc )
```
