### ISSUE TITLE
usr/bin/install reference in ruby config

### ISSUE THREAD

**Issue by nsouch** [Optware/Optware-ng#134]
<code>/opt/lib/ruby/2.3.0/i686-linux-gnu/rbconfig.rb</code> defines INSTALL as <code>/usr/bin/install -c</code> though it is not an option for our target. I think we could remove line <code>CONFIG["INSTALL"] = '/usr/bin/install -c'</code> and let ruby use its internal install procedure.

It works here for gem ffi install.

**Comment by alllexx88** [comment]
Should be fixed now, thanks
