### ISSUE TITLE
Request: libwebsockets

### ISSUE THREAD

**Issue by Johnsik** [Optware/Optware-ng#136]
For my project I need libwebsockets with OpenSSL support.
libwebsockets use cmake to build. And I don't understand how to work with cmake in Optware make file :(

**Comment by alllexx88** [comment]
I'll be away from PC most of the day, so won't be able to look into it till evening (it's GMT +2 here). For now, you can try to add it yourself if you like. As [wiki](https://github.com/Optware/Optware-ng/wiki/Adding-a-package-to-Optware-ng) suggests, you can see [make/6relayd.mk](https://github.com/Optware/Optware-ng/blob/master/make/6relayd.mk) for a cmake package example. `6relayd` has no package-specific cmake flags, so you can use it as a template and add specific flags you need.

**Comment by alllexx88** [comment]
Done: 0877c402c98e7aa91e25d60e46cef33d37110bba

**Comment by Johnsik** [comment]
Thank you!

**Comment by alllexx88** [comment]
@Johnsik You're welcome :smiley: I've cleaned cmake packages a bit, so the example [make/6relayd.mk](https://github.com/Optware/Optware-ng/blob/master/make/6relayd.mk) is more readable now. That being said, I had to patch `libwebsockets`, since it failed to locate libssl.

**Comment by saqebakhter** [comment]
I'm having simlar problem with encfs @alllexx88 what patch did you do ?
