### ISSUE TITLE
net-snmp: libnl-3.so.200 is missing

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#140]
Hi,

net-snmp is missing libnl dependency

$ ipkg upgrade
...
Configuring net-snmp
**/opt/sbin/snmpd: error while loading shared libraries: libnl-3.so.200: cannot open shared object file: No such file or directory**
postinst script returned status 127
ERROR: net-snmp.postinst returned 127
...

$ ldd /opt/sbin/snmpd
        linux-gate.so.1 (0xf76f8000)
        libnetsnmpagent.so.30 => /opt/lib/libnetsnmpagent.so.30 (0xf7685000)
        libnetsnmpmibs.so.30 => /opt/lib/libnetsnmpmibs.so.30 (0xf7445000)
        libnetsnmp.so.30 => /opt/lib/libnetsnmp.so.30 (0xf7366000)
        libdl.so.2 => /opt/lib/libdl.so.2 (0xf7361000)
        libcrypto.so.1.0.0 => /opt/lib/libcrypto.so.1.0.0 (0xf715b000)
        **libnl-3.so.200 => not found**
        libm.so.6 => /opt/lib/libm.so.6 (0xf710e000)
        libc.so.6 => /opt/lib/libc.so.6 (0xf6f59000)
        /opt/lib/ld-linux.so.2 (0xf76f9000)
        libnl-3.so.200 => not found
        libnl-3.so.200 => not found

$ ipkg install libnl
Installing libnl (3.2.25-1) to root...
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-i686/libnl_3.2.25-1_i686.ipk
Configuring libnl
Configuring net-snmp
postinst script returned status 1
ERROR: net-snmp.postinst returned 1
Successfully terminated.

$ ldd /opt/sbin/snmpd
        linux-gate.so.1 (0xf76df000)
        libnetsnmpagent.so.30 => /opt/lib/libnetsnmpagent.so.30 (0xf766c000)
        libnetsnmpmibs.so.30 => /opt/lib/libnetsnmpmibs.so.30 (0xf742c000)
        libnetsnmp.so.30 => /opt/lib/libnetsnmp.so.30 (0xf734d000)
        libdl.so.2 => /opt/lib/libdl.so.2 (0xf7348000)
        libcrypto.so.1.0.0 => /opt/lib/libcrypto.so.1.0.0 (0xf7142000)
        **libnl-3.so.200 => /opt/lib/libnl-3.so.200 (0xf7124000)**
        libm.so.6 => /opt/lib/libm.so.6 (0xf70d7000)
        libc.so.6 => /opt/lib/libc.so.6 (0xf6f22000)
        /opt/lib/ld-linux.so.2 (0xf76e0000)
        libpthread.so.0 => /opt/lib/libpthread.so.0 (0xf6f05000)

$ echo agentaddress  1161 >> /opt/etc/snmpd.conf
$ /opt/sbin/snmpd -c /opt/etc/snmpd.conf
$ ps -ef | grep opt.*snmp[d]
root     27913     1  0 23:20 ?        00:00:01 /opt/sbin/snmpd -c /opt/etc/snmpd.conf
$ snmpwalk -c public localhost:1161
...

**Comment by alllexx88** [comment]
Thanks for the report :smiley:
