### ISSUE TITLE
PHP module mb multibyte request

### ISSUE THREAD

**Issue by TeHashX** [Optware/Optware-ng#141]
As title say, owncloud v9.0.3 require PHP module mb multibyte, can be added?
Thanks

![screenshot 2016-07-12 18 29 14](https://cloud.githubusercontent.com/assets/1405188/16810568/00553f26-492d-11e6-808e-defab908f427.png)

**Comment by alllexx88** [comment]
According to [this](https://forum.owncloud.org/viewtopic.php?t=25517), the module is actually called `mbstring`, and `php-mbstring` package is available in Optware-ng. I remember I used owncloud 8 with mbstring support just fine.

**Comment by TeHashX** [comment]
Yes, you are right, as always :)
Solved with
````
ipkg install php-mbstring
/opt/etc/init.d/S80lighttpd restart
````

**Comment by Ajun10** [comment]
Thanks @alllexx88 and @TeHashX
