### ISSUE TITLE
opkg install error

### ISSUE THREAD

**Issue by chenxue1** [Optware/Optware-ng#145]
hi:
   all, i want to run openjdk on my router, and i found here. Then i download then openjdk arm V7 with hf and sf, and use the opkg to install the package, but it reports 
 * pkg_hash_fetch_best_installation_candidate: Packages for openjdk8-jdk found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package openjdk8-jdk.
what`s wrong with this, someone can help me?
  thks

**Comment by alllexx88** [comment]
Hi,

You have to bootstrap the feed complitely: whatever you're running on your router that uses opkg (OpenWRT, probably?) isn't compatible with Optware-ng (I mean, you can't install Optware-ng packages with your router's opkg). Even if you install the package manually, or some other way bypassing install errors, it just won't plain work. Optware-ng resides under `/opt`, so it won't conflict with OpenWRT, which installs to `/usr`. 
To bootstrap, make sure that `/opt` is writable and has some free space to it, and then run

```
wget -O - http://ipkg.nslu2-linux.org/optware-ng/bootstrap/buildroot-armeabi-ng-bootstrap.sh | sh
```

After this, you'll be able to install Optware-ng openjdk8:

```
/opt/bin/ipkg update
/opt/bin/ipkg install openjdk8-jdk
```

**Comment by alllexx88** [comment]
closing due to no response
