### ISSUE TITLE
Perl 5.22 undefined symbol: strlcat

### ISSUE THREAD

**Issue by Johnsik** [Optware/Optware-ng#150]
With Perl 5.22.1 (latest in Optware-ng) i see:
```
[git@NAS ~]$ gitolite/install -to $HOME/bin
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_US.UTF-8",
        LC_CTYPE = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
/usr/bin/perl: symbol lookup error: /opt/lib/perl5/5.22.1/i686-linux/auto/Cwd/Cwd.so: undefined symbol: strlcat
```
With Perl 5.20.1 (penultimate in Optware-ng) I see:
```
[git@NAS ~]$ gitolite/install -to $HOME/bin
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_US.UTF-8",
        LC_CTYPE = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

With 5.20.1 all work fine (with the exception of warnings of cource)

**Comment by alllexx88** [comment]
Hi,

This is doesn't look like a problem with Optware-ng: Cwd module works fine with Optware-ng perl (same i686 feed):

```
root@DiskStation:~# /opt/bin/perl
use Cwd;
print getcwd;
^D
/root
```

It's `/usr/bin/perl` that's reporting error -- not `/opt/bin/perl`, and I doubt that `/usr/bin/perl` is a link to `/opt/bin/perl` -- right? (Make sure with `ls -l /usr/bin/perl`). And it wrongly picks up an Optware-ng perl module, so it's of no surprise an error occurs.

Why this is happening is a different question. Did you set `PERL5LIB` or `PERLLIB` env variables? The only ways to add non-standard `@INC` locations is via these, or passing the `-I` flag to `perl`

**Comment by Johnsik** [comment]
`/usr/bin/perl`  is a link to `/opt/bin/perl` so it's the same.
No, I don't set `PERL5LIB` or `PERLLIB`.
But there is no problem on the same machine (and on the same session) with Perl 5.20.1 that I was build from Optware-ng sources. I'm only change 5.22 to 5.20 and do make.
Only try to install `gitolite` and you can see it.

**Comment by alllexx88** [comment]
Should be fixed now, thanks for the report

**Comment by Johnsik** [comment]
Сonfirm. Fixed!
