### ISSUE TITLE
Request: sshguard

### ISSUE THREAD

**Issue by ElTopo** [Optware/Optware-ng#152]
sshguard protects hosts from brute force attacks against SSH and other services, similar to denyhosts/fail2ban, but it's written in C thus it has tiny footprint and does not depend on python.

Official site:
http://www.sshguard.net/
current release
https://sourceforge.net/projects/sshguard/files/sshguard/1.7.0/
source code repo:
https://bitbucket.org/sshguard/sshguard/

Thanks

**Comment by alllexx88** [comment]
Almost a year has passed, but `sshguard` package added: 7b48ee8122401bc52659dfed0d4f6efb9ae9c1b4
For some reason `sshguard 1.7.1` refuses to be daemonized by `start-stop-daemon` or `daemonize` utilities on my test machine, so as a workaround it's being detached using shell.

To launch `sshguard` daemon, run `/opt/etc/init.d/S15sshguard start`, and `/opt/etc/init.d/S15sshguard stop` to stop it. Daemon loads `/opt/etc/sshguard/whitelist` file on start (see https://www.sshguard.net/docs/whitelist/)
