### ISSUE TITLE
libacl.so.1 missing

### ISSUE THREAD

**Issue by PiotrC1** [Optware/Optware-ng#154]
Starting cupsd at ARM7 optware-ng (Tomato by Shibby, v 1.37) pops up message:
/opt/sbin/cupsd: can't load library 'libacl.so.1'

Executing strace cupsd gives:
root@Tomato:/tmp/home/root# strace cupsd
execve("/opt/sbin/cupsd", ["cupsd"], [/* 17 vars */]) = 0
readlinkat(AT_FDCWD, "/proc/self/exe", "/opt/sbin/cupsd", 4096) = 15
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x40028000
open("/opt/lib/libiconv.so.2", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=904812, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x400b3000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\310\20\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 970752, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x40183000
mmap2(0x40183000, 899900, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x40183000
mmap2(0x4026f000, 2588, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xdc000) = 0x4026f000
close(3)                                = 0
munmap(0x400b3000, 4096)                = 0
open("/opt/lib/libcupsmime.so.1", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=17056, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x400c3000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0l\22\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 81920, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x40165000
mmap2(0x40165000, 15424, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x40165000
mmap2(0x40178000, 3716, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x3000) = 0x40178000
close(3)                                = 0
munmap(0x400c3000, 4096)                = 0
open("/opt/lib/libz.so.1", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=88784, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x40073000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\10\25\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 155648, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x400c7000
mmap2(0x400c7000, 86952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x400c7000
mmap2(0x400ec000, 1612, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x15000) = 0x400ec000
close(3)                                = 0
munmap(0x40073000, 4096)                = 0
open("/opt/lib/libgnutls.so.28", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=933032, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x40027000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\34n\1\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 999424, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x40270000
mmap2(0x40270000, 907724, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x40270000
mmap2(0x4035d000, 26412, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xdd000) = 0x4035d000
close(3)                                = 0
munmap(0x40027000, 4096)                = 0
open("/opt/lib/libpam.so.0", O_RDONLY)  = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=44260, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x4001b000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0`\32\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 110592, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x40061000
mmap2(0x40061000, 42308, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x40061000
mmap2(0x4007b000, 2088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xa000) = 0x4007b000
close(3)                                = 0
munmap(0x4001b000, 4096)                = 0
open("/opt/lib/libdl.so.1", O_RDONLY)   = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=13228, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x40092000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\334\v\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 81920, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x40364000
mmap2(0x40364000, 8741, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x40364000
mmap2(0x40376000, 4120, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0x40376000
close(3)                                = 0
munmap(0x40092000, 4096)                = 0
open("/opt/lib/libacl.so.1", O_RDONLY)  = -1 ENOENT (No such file or directory)
open("/opt/lib/libacl.so.1", O_RDONLY)  = -1 ENOENT (No such file or directory)
open("/opt/lib/libacl.so.1", O_RDONLY)  = -1 ENOENT (No such file or directory)
open("/lib/libacl.so.1", O_RDONLY)      = -1 ENOENT (No such file or directory)
open("/usr/lib/libacl.so.1", O_RDONLY)  = -1 ENOENT (No such file or directory)
open("/usr/X11R6/lib/libacl.so.1", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/lib/libacl.so.1", O_RDONLY)  = -1 ENOENT (No such file or directory)
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x40027000
write(2, "", 0)                         = 0
write(2, "/opt/sbin/cupsd", 15/opt/sbin/cupsd)         = 15
write(2, ": can't load library '", 22: can't load library ')  = 22
write(2, "libacl.so.1", 11libacl.so.1)             = 11
write(2, "'\n", 2'
)                      = 2
munmap(0x40027000, 4096)                = 0
exit(16)                                = ?
+++ exited with 16 +++
root@Tomato:/tmp/home/root#

After installing libacl everything goes OK.

**Comment by alllexx88** [comment]
Should be fixed now: run `ipkg update; ipkg upgrade `

**Comment by PiotrC1** [comment]
Confirm - works.
Thank you
