### ISSUE TITLE
ELF file OS ABI invalid

### ISSUE THREAD

**Issue by brilong** [Optware/Optware-ng#157]
I've recently installed Optware-ng on my QNAP TS-659 Pro (Intel D510 CPU).  This installed glibc-2.21 into /opt/lib, when when I set my LD_LIBRARY_PATH=/opt/lib:/usr/lib, the linker gives the following error:

which: error while loading shared libraries: /opt/lib/libm.so.6: ELF file OS ABI invalid

I'm trying to install various additional utilities including compiling MariaDB from scratch and I would like to use the updated glibc, but I'm wondering what I might be doing wrong.   Thanks.

**Comment by alllexx88** [comment]
@brilong You should unset `LD_LIBRARY_PATH`: Optware-ng doesn't need it, and setting `/opt/lib` first obviously screws your firmware `which`:

```
unset LD_LIBRARY_PATH
```

If you set `/usr/lib` first, I suspect it'll screw Optware-ng binaries

**Comment by brilong** [comment]
That makes sense.  I had downloaded a binary tarball (MariaDB 10.x) that required glibc 2.14+ and couldn't get it working.  Since it requires a mix of Optware and system libraries, I guess that makes sense.  Once I downloaded a version that worked with system glibc, I was able to start it up.
