### ISSUE TITLE
npm install fails (-ldns_sd missing)

### ISSUE THREAD

**Issue by woutercoppens** [Optware/Optware-ng#166]
I'm trying to install homebridge on my synology NAS, but I always get this error.

> npm install homebridge
> 
> > mdns@2.3.3 install /tmp/node_modules/mdns
> > node-gyp rebuild
> 
> make: Entering directory '/tmp/node_modules/mdns/build'
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_update_record.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
>   CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
>   SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
> /opt/bin/ld: cannot find -ldns_sd
> collect2: error: ld returned 1 exit status
> dns_sd_bindings.target.mk:184: recipe for target 'Release/obj.target/dns_sd_bindings.node' failed
> make: **\* [Release/obj.target/dns_sd_bindings.node] Error 1
> make: Leaving directory '/tmp/node_modules/mdns/build'
> gyp ERR! build error

At first try, I got an error on dns_sd.h missing, but that was solved by copying dns_sd.h from the avahi package into /opt/include.

**Comment by alllexx88** [comment]
OK, finally got to sorting this out: `ipkg update; ipkg install libavahi-compat-libdns-sd` installs the missing lib now. If you're still with me, please give it a try
