### ISSUE TITLE
[request] add go to gcc

### ISSUE THREAD

**Issue by The-MAD-Virus** [Optware/Optware-ng#169]
Hi, is it possible to add "go" to gcc build ?

```--enable-languages=c,c++,go```

**Comment by alllexx88** [comment]
Hi, it's possible, but not easy. The needed patches are there, in large thanks to Entware-ng, however, I need to add go to the cross-toolchain first, and most Optware-ng targets use Buildroot to compile toolchains, and AFAIK `gccgo` isn't yet added to Buildroot, so, I'd have to patch it quite extensively. Doable, but very time-consuming, won't probably have time for this in a while

**Comment by The-MAD-Virus** [comment]
ok, thanks and if i can help in any way it will be a pleasure.
i did try compile it my self, but i think i miss some thing while setting up my VM.

**Comment by alllexx88** [comment]
Hi,
I've added `go` to `gcc`. It took some patching, but it seems `go` works fine now

**Comment by alllexx88** [comment]
Closing the issue. As a side note, `gccgo` is now a separate package
