### ISSUE TITLE
can't load library 'libreadline.so.6' error when running freeradius 3.0.10-4

### ISSUE THREAD

**Issue by zebralight** [Optware/Optware-ng#176]
I was able to install freeradius 3.0.10-2 https://github.com/Optware/Optware-ng/issues/125 but upon installing freeradius 3.0.10-4, I'm getting the following message when trying to run "radiusd -X" immediately upon installing freeradius:

`/tmp/mnt/sda2/optware-ng.arm/bin/radclient: can't load library 'libreadline.so.6'`

any help would be much appreciated, including any leads to previous builds of freeradius.

**Comment by zebralight** [comment]
I found the solution to the libreadline.so.6 error [here](https://www.hqt.ro/how-to-install-new-generation-optware/#comment-3085508815), but now I'm getting a "segmentation fault" error message, which I tried to solve by uninstalling and reinstalling freeradius.  I had also tried to install older versions of freeradius (.10-3 and .10-2), which ran just fine, but am now getting the segmentation fault error message for those as well.

**Comment by alllexx88** [comment]
`Segmentation fault` was caused by firmware `libpcre` being loaded. Installing `pcre` package is enough to fix this. Upgraded `freeradius` along the way too
