### ISSUE TITLE
Possible dbus dependency problem

### ISSUE THREAD

**Issue by davygravy** [Optware/Optware-ng#177]
Before moving from Optware to Optware-ng, I am testing the various packages needed for Bonjour (MacOS) and Airprint capability.  I noticed that the ipkg installation of dbus pulls in sm, x11 and a fairly weighty pile of other packages.

Is this the intent?  For routers (mipsel/Broadcom running TomatoUSB or DD-WRT for instance), it seems a bit heavy-handed.  Also, for comparison, Debian does not list either of these packages as dependencies, but rather as suggestions.

Would changing x11 and sm to suggested's rather than dependency's break anything?

**Comment by alllexx88** [comment]
The reason to depend on X11 and sm was [dbus-launch](https://dbus.freedesktop.org/doc/dbus-launch.1.html) command that's linked against `libX11`, `libSM` and `libICE`. Now `dbus-launch` is available as a separate package, and `x11` dependencies for `dbus` package are removed
