### ISSUE TITLE
mysql _connect

### ISSUE THREAD

**Issue by mfuentesraffio** [Optware/Optware-ng#178]
Hello, I have installed opteware-ng with ligttpd php mysql but php does not recognize mysql_connect but if you know mysqli_conec, is it possible to enable the mysql_connect function for my db to work again?

**Comment by alllexx88** [comment]
mysql 5.7 doesn't include the old client interface `libmysql` library: only the "new" `libmysqlclient`, so `mysql` php extension, which uses the former, simply can't be built. A proper solution to your problem is to migrate to using the `mysqli` extension
