### ISSUE TITLE
Request: sd-idle

### ISSUE THREAD

**Issue by drfra** [Optware/Optware-ng#179]
I was searching throu the package repository but could not find anything to spin down the external HDD . There are only scsi-idle and spindown, both of them don´t work as they were written for 2.4 kernel AFAIK, hdparm works just partially. Sd-idle worked without issues for me when I was testing entware-ng. Reportedly (Merlin himself on snbforums), more than 90% of drives can be spun down with sd-idle.

**Comment by alllexx88** [comment]
Done: d30c545e60fd8bf5dccbdbc908e00ae75412f243
