### ISSUE TITLE
bind

### ISSUE THREAD

**Issue by pwallner** [Optware/Optware-ng#181]
bind package was missing paramater "--enable-filter-aaaa" during compilation, I compiled a new one, either you use my version or you can compile a new one by yourself.

This Parameter is necessary for me to filter ipv6 Connections with netflix and he ipv6 tunnels. See [Info](https://gist.github.com/jamesmacwhite/6a642cb6bad00c5cefa91ec3d742e2a6)

Regards
Patrick
[bind_9.11.0-P1_arm.zip](https://github.com/Optware/Optware-ng/files/722127/bind_9.11.0-P1_arm.zip)

**Comment by alllexx88** [comment]
Done
