### ISSUE TITLE
nginx -- missing ipv6 support

### ISSUE THREAD

**Issue by pwallner** [Optware/Optware-ng#182]
nginx was compiled without ipv6 support. I have compiled a new one, either you use my version or you compile a new version by yourself.

Thx, regards
Patrick
[nginx_1.11.8_arm.zip](https://github.com/Optware/Optware-ng/files/722131/nginx_1.11.8_arm.zip)

**Comment by alllexx88** [comment]
Done: 7371b5f0d0146513b8ea1ce14f98afdd5770ee8d
