### ISSUE TITLE
UPX 3.91 bug

### ISSUE THREAD

**Issue by pwallner** [Optware/Optware-ng#185]
Found an bug in upx 3.91. The upx team fixed that bug in the current devel branch (3.94).

Please update to latest version. I have included the fixed compiled version.

[upx3.94-git-devel](https://www.dropbox.com/s/e2rwkl773w3r869/upx394.zip?dl=0)

Regards
Patrick

**Comment by alllexx88** [comment]
Upgraded to 3.94 (released on May 12th)
