### ISSUE TITLE
Entware-ng <-> Optware-ng merging: Trustware

### ISSUE THREAD

**Issue by alllexx88** [Optware/Optware-ng#186]
Cannot afford to be less/more (un)specific, but I assume that the need to sustain Entware-ng || Optware-ng (and vice versa) separately is soothing now. I believe, a common project, based on the strong sides of the both projects is needed. The need in balance between  Entware-ng (<=OpenWRT) object-oriented transparent approach, and Optware-ng (<=Optware) fine control, should give birth to what I'd name "Trustware": a joint force project, where all the tremendous work on the each of them would be naturally summed up. Sufficient experience feels to be accumulated already.

**Comment by alllexx88** [comment]
Please see https://github.com/Entware-ng/Entware-ng/issues/573

**Comment by cfpp2p** [comment]
@alllexx88 Should I continue updates or where; in [this format](https://github.com/cfpp2p/Optware-ng/commit/d34985dfe21b45c6a33eac5d4ca00cb069e228e0) ?

**Comment by alllexx88** [comment]
@cfpp2p race conditions are really nasty, so I see you know better than me. Please do as you see fit.

With the best of regards,
Alex

**Comment by alllexx88** [comment]
@cfpp2p I'd be glad to retire from being the admin here, due to impossible fatigue. So if feel like carrying on with this as you see fit, please do. You've been doing a great job on pull requests while I've been away, so I put my trust in you.

Sincerely,
Alex

**Comment by alllexx88** [comment]
Just tell me if I need to confirm something, to make this "official" ;)

Hereby I (")officially confirm(") you guys can carry on as you feel, I'd rather rest a bit, 'cause I feel as a Glacier :dagger: :dancer: :dancing_men: :dancing_women: :dango: and so on :rofl:

**Comment by alllexx88** [comment]
And when I'm rested, we'll manage somehow. A serious promise :1st_place_medal:

**Comment by cfpp2p** [comment]
@alllexx88 Thanks so much for all your hard work. It's been a really great project and I'm sure you could use many compliments of appreciation !

**Comment by alllexx88** [comment]
@cfpp2p So many thanks to you mutually! And the all of the very best of the luck I can imagine now shall follow you -- this is my hope and trust...
