### ISSUE TITLE
openvpn problem

### ISSUE THREAD

**Issue by armando-basile** [Optware/Optware-ng#189]
Hi, i trying to use openvpn from optware-ng environment on my android box.
I can install it but when i try to launch i receive error on TUN/TAP use, seems that doesn't present. 

during install it say:
Installing openvpn (2.2.0-2) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabihf/openvpn_2.2.0-2_arm.ipk.
openvpn: unsatisfied recommendation for kernel-module-tun
...

could you help me ?

if problem is openvpn, i could also try to use another vpn client but i founded only this.

**Comment by armando-basile** [comment]
no news about .... ?

**Comment by alllexx88** [comment]
Optware-ng on android isn't really supported, though most Optware-ng packages can indeed run on android too. I suspect that your firmware is missing tun.ko kernel module. You can look [here](https://forum.xda-developers.com/showthread.php?t=1416540) for possible solution
