### ISSUE TITLE
optware-ng

### ISSUE THREAD

**Issue by satfreak** [Optware/Optware-ng#197]
At the moment i playing around with optware-ng on qnap with qts 4.3.
This because entware-ng, is missing a lot off programs witch are included in optware-ng.

I think if the small little mising programs and mistake can be fixed.
optware-ng would be a mutch beter option on qnap the entware-ng.
As entware-ng does not even care if one ask the add a program.
So my qeustion is, can we make optware-ng compleet, so it can be used on qnap.
I already looking how to make a installation packet for qnap.
Any help is welcome.

**Comment by satfreak** [comment]
Oke first alpha version is ready.
Works on qnap servers with intel cpu.

https://www.dropbox.com/s/jb52kjkrqco4x9h/Optware-NG_0.01alpha.qpkg?dl=0

**Comment by alllexx88** [comment]
Well done! I don't own a qnap, so can't test, but that's great 👍

**Comment by satfreak** [comment]
Oke a beta version is ready, no with support for qnap arm5 and arm7 cpu.
But as i only own a ts-453a with a intel cpu, so could not tested it.
Please deinstall alpha version first.

https://www.dropbox.com/s/m3o4pj13ds7gkg6/Optware-NG_0.03Beta.qpkg?dl=0

**Comment by satfreak** [comment]
Close this item, as its not a issue.
More info on the qnap forum.
