### ISSUE TITLE
request for serval packages

### ISSUE THREAD

**Issue by satfreak** [Optware/Optware-ng#199]
I love Optware-NG on my qnap.
Working on a qpkg installation file, to port it to qnap servers.

I can find most packages whitch Entware-NG is missing.

But one is  not presented, so thats why i do a request here.
I miss mediainfo
Needed when one wants to do audio handeling through a script like me.

So is there away they could be included in the repository ?
Thanks .

**Comment by alllexx88** [comment]
Run it's working good for you 😄 Package `mediainfo` added 😉 See bb7ed97c3bb9be7977c615b8a0550164af80271a 143e116e4ea54396d0b9ce426ff43ea3052d422a

**Comment by satfreak** [comment]
Great this makes optware-ng for me a complet replacement.
So glad that on optware-ng, there a persons taking care of requested packets.

Thanks.
