### ISSUE TITLE
support for ape audio

### ISSUE THREAD

**Issue by satfreak** [Optware/Optware-ng#201]
Well testing and playing around, i noticed that the file mac for ape is not there.
As ape is still used, want to reqeust if its possible to add mac to the repository ?

**Comment by alllexx88** [comment]
Which package exactly do you request? A link to the source-code?

**Comment by satfreak** [comment]
It monkey audio.
https://en.wikipedia.org/wiki/Monkey%27s_Audio

This is the source file i using

[mac-3.99-u4-b5-s7.tar.gz](https://github.com/Optware/Optware-ng/files/1220705/mac-3.99-u4-b5-s7.tar.gz)

**Comment by alllexx88** [comment]
Done: see c29607203ccdc3595c32f763b3952391ff823fa1

**Comment by satfreak** [comment]
What a great support.
Thanks once again, for al the good work on optware-ng.
