### ISSUE TITLE
chromaprint

### ISSUE THREAD

**Issue by satfreak** [Optware/Optware-ng#204]
Is there a way, on which chromaprint can be included in the repository ?
As fpcalc is part off this program and used by beets and filebot.
And i think a lot off users are lokking for away to get fpcalc on the server/systeem.

https://github.com/acoustid/chromaprint
Look on it to build it my self, but it needs cmake, which is not part off the repository

**Comment by alllexx88** [comment]
Done: e2d6436fa0b7c22c9410c636cd9e2c9e70b8d3f4

**Comment by satfreak** [comment]
Realy great, i want to give you a big compliment about the way you handle request.

Mutch better then any other fork of optware.
So glad that the support is so good handled here.

When i`m done with making it work for qnap, wanna have a look how i can contribute to the project.

Alllexx88 you`re the best. :-)

**Comment by alllexx88** [comment]
@satfreak Thank you for your kind words: it's always a pleasure to see that your work matters for someone 😃 

> When i`m done with making it work for qnap, wanna have a look how i can contribute to the project.

That's great to hear, looking forward to it. Useful package requests is a kind of contribution too, by the way :wink: 

P.S. I'm leaving for a vacation today, won't be doing requests or bug fixes for about a week, but do feel free to open new issues: I'll look into them when I'm back
