### ISSUE TITLE
question: which package has rc.unslung script?

### ISSUE THREAD

**Issue by ElTopo** [Optware/Optware-ng#205]
Hello,

I found that I don't have rc.unslung script (/opt/etc/init.d/rc.unslung) in my optware-ng systems.

Does the script belong to any package, or I have to manually create it?

Thanks.

**Comment by alllexx88** [comment]
Hi,

You mean a script to start/stop all optware services? AFAIK, it's not provided by optware. You can try something like [this](https://github.com/Entware/rtndev/blob/master/uclibc-opt/files/rc.unslung) (haven't tested it)

**Comment by ElTopo** [comment]
@alllexx88  so I have to manually create... Thanks!
