### ISSUE TITLE
perl-net-ssleay wrong ssleay.so

### ISSUE THREAD

**Issue by satfreak** [Optware/Optware-ng#207]
After installing perl-net-ssleay, ssleay.so is installed.
Should be a 64 version, but on check it says ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV),

**Comment by alllexx88** [comment]
There's currently no x86_64, or any 64-bit in general, feeds. ` ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV)` is valid i686 binary
