### ISSUE TITLE
glibc-opt and libc-dev wrong elf

### ISSUE THREAD

**Issue by satfreak** [Optware/Optware-ng#208]
In the packeg glibc-opt and libc-dev, all the files are ELF 32.
opt/lib/librt.so: ELF 32-bit LSB shared object, Intel 80386

This should be ELF 64 or x86_64

**Comment by alllexx88** [comment]
Nope, it's right for `i686`. No 64bit feeds (yet) in Optware-ng

**Comment by satfreak** [comment]
Yes if noticed that i686 is not 64.
Stupid me thought is was.
But is there any time that there will be a feed with x86_64 programs.
Or is there a way we can make it?

As al other programs on Qnap are.
And no in combination perl, can got a conflict trying to compile can modules.

**Comment by alllexx88** [comment]
I have this somewhere on the to-do list, just don't have the time for it right now

**Comment by satfreak** [comment]
Is there same way i can help on this.
Never done something like this, but have read to way to make a pc to make packets.
But don know what is needed to add x86_64 to the build.
And was planning to prepare a pc, to have a look on how to make ipk files.

**Comment by alllexx88** [comment]
Adding a target usually means:
1) Add a recipe to build toolchain
2) Sort out compilation issues that always arise for a new target. Especially since currently all targets are 32 bit

Step 1) is more or less simple, but 2) usually takes a lot of time and sometimes effort

**Comment by satfreak** [comment]
Oke but if they could get it working on entware-ng, then is also must be possible to make it work in Optware-NG

**Comment by alllexx88** [comment]
Sure, it's possible. However, entware-ng comes from openwrt, where they have 64bit platforms, while old optware, from whih optware-ng spun off, has none... So it'll be a bit of a hassle
