### ISSUE TITLE
Apache module

### ISSUE THREAD

**Issue by me11ved** [Optware/Optware-ng#212]
Please check the apache modules. For example, do not work:

- rewrite_module
- ssl_module

**Comment by alllexx88** [comment]
What exactly doesn't work? A minimal working example to illustrate the issue? There're no errors regarding loading the modules in `error_log`

**Comment by me11ved** [comment]
Alex, I can not provide a log of errors, since they are empty. I put all that is. 
My site is powered by WordPress. Next to the first page shows a 404 error

**httpd.conf**
LoadModule rewrite_module libexec/mod_rewrite.so 
site directory:

> <Directory /opt/var/sites/subdomain/demo>
		Options Indexes FollowSymLinks
		Require all granted
		AllowOverride All
</Directory>

Error log Apache:

> [Thu Sep 21 12:54:59.560420 2017] [mpm_worker:notice] [pid 1757:tid 716050432] AH00298: SIGHUP received.  Attempting to restart
[Thu Sep 21 12:55:00.167597 2017] [ssl:warn] [pid 1757:tid 716050432] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Thu Sep 21 12:55:00.189679 2017] [mpm_worker:notice] [pid 1757:tid 716050432] AH00292: Apache/2.4.27 (Unix) PHP/5.6.31 OpenSSL/1.0.2h configured -- resuming normal operations
[Thu Sep 21 12:55:00.189862 2017] [core:notice] [pid 1757:tid 716050432] AH00094: Command line: '/opt/sbin/httpd'
[Thu Sep 21 12:59:36.400606 2017] [mpm_worker:notice] [pid 1757:tid 716050432] AH00298: SIGHUP received.  Attempting to restart
[Thu Sep 21 12:59:36.942401 2017] [ssl:warn] [pid 1757:tid 716050432] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Thu Sep 21 12:59:36.953106 2017] [mpm_worker:notice] [pid 1757:tid 716050432] AH00292: Apache/2.4.27 (Unix) PHP/5.6.31 OpenSSL/1.0.2h configured -- resuming normal operations
[Thu Sep 21 12:59:36.953344 2017] [core:notice] [pid 1757:tid 716050432] AH00094: Command line: '/opt/sbin/httpd'

**Comment by me11ved** [comment]
I here set 

>  <Directory "/ opt / var / sites">
>   AllowOverride All
>  </Directory>

It works. Please close the ticket

**Comment by alllexx88** [comment]
Great, glad it works for you.
