### ISSUE TITLE
imap_open, error:  invalid remote specification (errflg=2)

### ISSUE THREAD

**Issue by me11ved** [Optware/Optware-ng#213]
Help. If you try to connect to the box, an error occurs.

> Warning: imap_open(): Couldn't open stream {imap.yandex.ru:993/imap/ssl/novalidate-cert} in /tmp/mnt/mydisk/optware-ng.arm/var/sites/test/info.php on line 9
Connection failed	
Notice: Unknown: Can't open mailbox {imap.yandex.ru:993/imap/ssl/novalidate-cert}: invalid remote specification (errflg=2) in Unknown on line 0

> 
[]$ ipkg list-installed
apache - 2.4.27-1
apr - 1.6.2-1
apr-util - 1.6.0-1
bash - 4.4.12-2
busybox-base - 1.25.0-3
bzip2 - 1.0.6-2
cacerts - 20170918-1
cyrus-sasl-libs - 2.1.26-2
e2fslibs - 1.42.12-1
e2fsprogs - 1.42.12-1
expat - 2.2.0-1
findutils - 4.2.32-1
gdbm - 1.8.3-4
gettext - 0.19.8.1-1
glib - 2.47.3-1
htop - 2.0.1-1
icu - 56.1-3
imap-libs - 2007a1-2
libcurl - 7.55.0-2
libdb - 5.3.21-1
libevent - 2.0.20-2
libffi - 3.2.1-1
libiconv - 1.13.1-1
libintl - 0.19.8.1-1
libmcrypt - 2.5.8-1
libnsl - 1.0.15-1
libpam - 1.1.8-3
libstdc++ - 6.0.21-6
libtool - 2.4.6-4
libunistring - 0.9.4-2
libxml2 - 2.7.8-1
libxslt - 1.1.26-3
mc - 4.8.17-3
mysql - 5.7.9-7
ncurses - 5.7-5
ncurses-base - 5.7-5
ncursesw - 5.7-2
openldap-libs - 2.4.40-3
openssl - 1.0.2h-1
pcre - 8.36-1
php - 5.6.31-9
php-apache - 5.6.31-5
php-curl - 5.6.31-9
php-dev - 5.6.31-9
php-fcgi - 5.6.31-9
php-imap - 5.6.31-9
php-mbstring - 5.6.31-9
php-mcrypt - 5.6.31-9
php-mysql - 5.6.31-9
psmisc - 22.21-2
readline - 6.1-2
slang - 2.2.4-4
sqlite - 3.8.1-2
uclibc-opt - 1.0.15-2
zlib - 1.2.8-2

**Comment by alllexx88** [comment]
`imap` php extension was built without SSL support. I enabled SSL support with c15e0b008d3e447dd4c4c23979ea3493bb65b749. Upgrade `php-imap` package, and it should work (`buildroot-armeabi-ng` feed updated binaries are online).

**Comment by me11ved** [comment]
Please close this tiket. Imap working. Thank you!

**Comment by alllexx88** [comment]
You're welcome.
