### ISSUE TITLE
"Not selecting apr 1.5.2 as installing it would break existing dependencies"?

### ISSUE THREAD

**Issue by ElTopo** [Optware/Optware-ng#220]
Hello,

I recently got "Not selecting apr 1.5.2 as installing it would break existing dependencies." when I did 
ipkg update && ipkg upgrade

I have apr 1.6.2-2 installed. 

I don't know which package causes this warning. Please help me find out the package and solve this issue, thanks!

**Comment by alllexx88** [comment]
Hi,

Such things happen from time to time for no apparent reason: it's an opkg bug probably. You can either safely ignore this message, or manually edit `/opt/lib/ipkg/status`, search for lines like

```
Package: apr
Version: 1.5.2
...
```

And delete the reference

**Comment by ElTopo** [comment]
@alllexx88 OK thanks.
