### ISSUE TITLE
python i686 issues

### ISSUE THREAD

**Issue by anvial1** [Optware/Optware-ng#223]
i have installed the python i686 last update package and it does not work

please help me to solve the problem

Antonio

**Comment by alllexx88** [comment]
It works for me. Maybe, some details?

**Comment by satfreak** [comment]
python 2.7.12 have problems for example if you try to run pip, it give errors on de pkg-recoures init script. Accoording to information this is fixed in 2.7.14.
For me to i can not use or run pip anymore.

https://www.python.org/ftp/python/2.7.14/

**Comment by alllexx88** [comment]
`python27` upgraded to 2.7.14

**Comment by satfreak** [comment]
And problem with python fixed, every thing is working like a charm.
Thanks for the fast adjustement

Ruud

**Comment by alllexx88** [comment]
Good. You're welcome

**Comment by anvial1** [comment]
Solved also for me. Thanks so much
