### ISSUE TITLE
File not found in Unknown on line 0

### ISSUE THREAD

**Issue by me11ved** [Optware/Optware-ng#227]
Hi! Please check the PHP library. 
When I try to execute a query in the console, 
I get an error. I can not run the cron.
Thank you!

console query:

> /opt/bin/php -q /opt/var/sites/path/cron.php >> /opt/var/log/cron.log 2>&1

error:

> PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/lib/php/extensions/mcrypt.so' - File not found in Unknown on line 0

```
ls -s /opt/lib/php/extensions/
mcrypt.so - exist
```
```
ipkg install php-mcrypt --force-reinstall
no result
```

**Comment by alllexx88** [comment]
Hi,
Should be fixed now: please upgrade `libtool` package and test:
```
ipkg update
ipkg upgrade libtool
/opt/bin/php -m
```
