### ISSUE TITLE
mlocate is no longer working

### ISSUE THREAD

**Issue by Lalarian** [Optware/Optware-ng#228]
Hello!
Until recently updatedb and mlocate where working fine. But without changing the system, it doesn't anymore, so I assume it's a packet problem.

I always get
"memory exhausted" when using updatedb or locate.
Could you please check this
Thank you :)

**Comment by alllexx88** [comment]
Hi,
Should be fixed now: upgrade to `0.26`

**Comment by Lalarian** [comment]
It's working!
Thank you :)
