### ISSUE TITLE
Pyload Update available

### ISSUE THREAD

**Issue by Lalarian** [Optware/Optware-ng#230]
Hello again! :)
Since a few days,  Pyload is claiming that there was an update available.

ipkg update didn't pull a new version.
Thanks! :)

I have found the issue:
[https://github.com/pyload/pyload/issues/2994](url)

> If you already have a working pyLoad installation (and used UpdatedManager in the past), you should replace UpdateManager.py which resides in the userplugins/hooks directory with
 [https://github.com/pyload/pyload/raw/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py](url)

So if someone could replace UpdateManager.py with the updated one in optwareng repo, it would install a working Pyload again.

**Comment by alllexx88** [comment]
Hi,

I simply upgraded `pyload` to latest git commit: upgrade to current `0.4.9+git20171028` package version, and it should be fine. Thanks for the report 😃

**Comment by N0News** [comment]
Hi, after upgrading python2.7 and pyload i have this error:

`/opt/bin/python2.7: can't open file 'pyLoadCore.py': [Errno 2] No such file or directory`

I use buildroot-armv5eabi-ng-legacy on Synology DS212J. Any ideas?

**Comment by N0News** [comment]
@alllexx88 thx, will test it later.

**Comment by alllexx88** [comment]
Thanx for testing, @N0News 
Closing the issue.
