### ISSUE TITLE
wget: HTTPS support not compiled in.

### ISSUE THREAD

**Issue by Lalarian** [Optware/Optware-ng#231]
Hello!

Is ist by intention, that wget doesn't have HTTPS support?

For example try:
`wget https://github.com/pyload/pyload/archive/master.zip
`

And you'll get:
> https://github.com/pyload/pyload/archive/master.zip: HTTPS support not compiled in.

I mean it's rather useless like this..

**Comment by alllexx88** [comment]
Hi,

Yes, it is by intention. There're two conflicting packages for wget: `wget` (wihout HTTPS support) and `wget-ssl` (with HTTPS support). So it's not an issue actually 😃 Just remove `wget` and install `wget-ssl`:

**Comment by Lalarian** [comment]
Ah ok, thank you! :)
