### ISSUE TITLE
Add chan-dongle module to asterisk11

### ISSUE THREAD

**Issue by me11ved** [Optware/Optware-ng#233]
Hi Alex.
I did not find the chan-dongle module for asterisk11. 
I can not create a voip gateway with my huawei 1550  3g modem. 
Thank you!

**Comment by alllexx88** [comment]
Hi,
Done: see 3fee9187f6d719bd01e5df961a775e0a2e738bfe

```
ipkg update
ipkg install asterisk11-chan-dongle
```

**Comment by me11ved** [comment]
Hi, Alex.
Thanks for the quick help.
I connected the modem. But it is not defined correctly.
`; dongle required settings
[HuaweiE1550]
audio=/dev/ttyUSB1		; tty port for audio connection; 	no default value
data=/dev/ttyUSB2		; tty port for AT commands; 		no default value
`
`ls -la /dev | grep ttyUSB* - not found`

In this task.:
Can you fix the correct connection? 
Thank you

**Comment by alllexx88** [comment]
Did you switch dongle mode to modem-only? You have to disable CD-ROM and CardReader. Quick googling shows you have to issue following AT command:

```
AT^U2DIAG=0
```

**Comment by me11ved** [comment]
These settings have been completed. When the router was on entware-ng. The modem was determined correctly.

**Comment by alllexx88** [comment]
It's not correct to say that router is/was on entware-ng/optware-ng. The router is on your firmware, and entware-ng/optware-ng build on top of it, using your firmware kernel, and some firmware commands too (though the latter can be substituted with optware-ng/entware-ng counterparts if need be). `/dev/ttyUSB*` discovery is governed by kernel -- not entware-ng or optware-ng, and, for example, in case of TomatoUSB firmware it can be enabled/disabled in `USB and NAS -> USB support` tab. So you should check your firmware.

P.S. Also, you may like to know that `grep ttyUSB*` command doesn't exactly do what you probably intended. It searchs for `ttyUS`, `ttyUSB`, `ttyUSBB`, `ttyUSBBB` and so on: `<symbol>*` in `grep` basic regexp mode (default) stands for "any number of `<symbol>`"

**Comment by me11ved** [comment]
Thanks for the detailed answer. 
I close the ticket. 
-
I'll ask for another package: usb-modeswitch
