### ISSUE TITLE
request for dir2ogg

### ISSUE THREAD

**Issue by satfreak** [Optware/Optware-ng#237]
Would it be possible to at dir2ogg, as it a very nice program to convert music.

https://github.com/julian-klode/dir2ogg

**Comment by alllexx88** [comment]
Package `dir2ogg` added: b649cdcc609986a6eab5b0a0dc4abd05d16cdfc7

**Comment by satfreak** [comment]
Thanks you`re the best.
Read this [url=https://forum.qnap.com/viewtopic.php?f=124&t=137710]Read this[/url]

**Comment by alllexx88** [comment]
> Read look here https://forum.qnap.com/viewtopic.php?f=124&t=137710

Well done creating a QNAP Optware-ng package! Is it stable enough to mention it in the Readme?

**Comment by satfreak** [comment]
I do think so, for me i`m very happy that i got it on my Qnap.
The only thing that some application, are complaining that it`s not a ELF64.

Still looking and reading a lot about how to get a ELF64 version off it.

**Comment by satfreak** [comment]
Hope you can keep it up. And not to many make a new issue.
Optware-NG is now part of the QNap AppCenter, and see that the amount off downloads is getting high.
