### ISSUE TITLE
CUPS 2.2.4-3 (armeabi flavour) no access to subpages, no printing

### ISSUE THREAD

**Issue by PiotrC1** [Optware/Optware-ng#238]
After opening address `http://cupsserver:631/jobs` CUPS returns error `500 Internal Error`. In log file following sequence appears:

> D [10/Dec/2017:10:06:50 +0100] [CGI] Started /opt/lib/cups/cgi-bin/jobs.cgi (PID 2853)
I [10/Dec/2017:10:06:50 +0100] [Client 1] Started "/opt/lib/cups/cgi-bin/jobs.cgi" (pid=2853, file=14)
D [10/Dec/2017:10:06:50 +0100] [Client 1] Waiting for CGI data.
D [10/Dec/2017:10:06:50 +0100] [Client 1] CGI data ready to be sent.
D [10/Dec/2017:10:06:50 +0100] PID 2853 (/opt/lib/cups/cgi-bin/jobs.cgi) stopped with status 127 (File too large)
D [10/Dec/2017:10:06:50 +0100] [Client 1] con->http=0x2a0ac8b8
D [10/Dec/2017:10:06:50 +0100] [Client 1] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=2147483647, response=(nil)(), pipe_pid=2853
, file=14
D [10/Dec/2017:10:06:50 +0100] [Client 1] Waiting for CGI data.
D [10/Dec/2017:10:06:50 +0100] [Client 1] cupsdSendHeader: code=500, type="text/html", auth_type=0
D [10/Dec/2017:10:06:50 +0100] [Client 1] Waiting for request.
D [10/Dec/2017:10:06:50 +0100] [Client 1] Closing because Keep-Alive is disabled.
D [10/Dec/2017:10:06:50 +0100] [Client 1] Closing connection.
D [10/Dec/2017:10:06:50 +0100] cupsdSetBusyState: newbusy="Dirty files", busy="Active clients and dirty files"

Installed packages: 

> cups cups-doc cups-pdf cups-filters cups-filters-doc ghostscript-fonts gutenprint cups-driver-gutenprint splix

Same problem (`file too large`) appears while printing

**Comment by alllexx88** [comment]
I confirm this issue. The same happens with `cups-2.2.6`. I've reported this upstream, let's see if we can get some help

**Comment by PiotrC1** [comment]
Maybe a temporary solution will be roll-back to last working version?

**Comment by alllexx88** [comment]
It's fixed now. Just upgrade to `2.2.6-2`
