### ISSUE TITLE
CUPS 2.2.4-3 (armeabi flavour) wrong SSL certificates name

### ISSUE THREAD

**Issue by PiotrC1** [Optware/Optware-ng#239]
My host name is `TomatoUSB`. SSL certificates created by CUPS in `/opt/etc/cups/ssl` are `TomatoUSB.crt` and `TomatoUSB.key` while CUPS awaits them to be `server.crt` and `server.key`. The bug causes following entry in log:

> E [10/Dec/2017:11:21:29 +0100] [Client 1] Unable to encrypt connection: Error in the pull function.

**Comment by alllexx88** [comment]
This issue is something I'm not seeing on my side. CUPS creates and loads `unknown.crt` and `unknown.key` (where `unknown` is my router hostname) without any issue. Can you try cups `2.2.6-1` to see if this issue remains?

**Comment by PiotrC1** [comment]
Well - now, after deleting certificates they are not re-generated on cups stratup. Previously they were generated again on startup.

**Comment by alllexx88** [comment]
`cups` generates the certificates only when they're needed. Try accessing `https://<router_ip>:631/admin` -- znd the certificates should be created
