### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by steom** [Optware/Optware-ng#24]
for ARMv7 EABI softfloat router, performance-wise which toolchain is better?  Your uClibc-ng-1.0.6 with gcc-5.2.0 or glibc 2.22 with gcc 4.8.5 and kernel sources 2.6.36?

**Comment by alllexx88** [comment]
uClibc was originally designed to be used in embedded systems. It is less resource-demanding, and therefore performs better. glibc is more feature-rich, but requires a more powerful system. Thus, to my understanding, uClibc toolchain should be better for a router.

**Comment by steom** [comment]
i've asked this because i've seen the new entware-ng project
and i just wonder what are the differences with optware-ng?
what are the features distinguish the projects?
They seem to be the same thing.

**Comment by alllexx88** [comment]
Apart from uclibc-ng vs. glibc difference, the difference also lies in different packages available. You can try both and choose which you like most. If there're some packages missing in Optware-ng, create an Issue, and I'll try to add it as soon as I can. Lately, I've been busy with OpenJDK8, finally got it to work with Zero VM for all targets, now I'm trying to make it work with JamVM instead. When I'm done with it, I'll continue with other requested packages

**Comment by steom** [comment]
Regarding ARMv7 routers the performance of optware-ng is better. So i choose optware-ng all the ways.
and i think so should do all the asuswrt, tomato and dd-wrt users out there.

it's a shame that exist two distinct project for make the same thing instead to join the efforts...an ordinary linux story...

**Comment by alllexx88** [comment]
Optware was there long before Entware. At some point, Optware became deprecated, since the main person behind it (project manager Brian Zhou) retired. Entware guys chose to create a new project based on OpenWRT instead of upgrading Optware. Since I knew Optware build system well, I decided to try to resurrect it, hence the Optware-ng was born.

**Comment by steom** [comment]
Yes, i know the story. 
Infact now that optware it's reborn i don't see the need of entware honestly.

**Comment by TeHashX** [comment]
In my opinion should be unified and named openware, enopware, opentware or enoptware :)
