### ISSUE TITLE
Circular build reference (gettext => libcroco => glib => gettext)

### ISSUE THREAD

**Issue by rivy** [Optware/Optware-ng#242]
While trying to update `lftp`, I've encountered a build dependency loop:

"gettext" makes "libcroco-stage" which makes "glib-stage" which makes "gettext-stage" which again makes "libcroco-stage", etc.

I broke it by commenting out the [`$(MAKE) gettext-stage` line in "make/glib.mk"](https://github.com/Optware/Optware-ng/blob/31aea0278827a439dcc16e562a6bf687c42e3509/make/glib.mk#L154):

https://github.com/Optware/Optware-ng/blob/31aea0278827a439dcc16e562a6bf687c42e3509/make/glib.mk#L153-L155

That seems like a hack, and I don't know the extent of the consequences. But, not fully understanding the build process, I'm not sure of a better method. Do you have a better solution?

I'm happy to PR it.

**Comment by alllexx88** [comment]
@rivy Thank you for the report! Fixed by using shipped `glib` and `libcroco` when building `gettext`
