### ISSUE TITLE
Bind package

### ISSUE THREAD

**Issue by dduck669** [Optware/Optware-ng#246]
Hi,
the bind package is compiled "--with-gost", but when I start it, it doesn't.
Logs says that:
Jan  3 14:08:51 wifi1 named[5510]: ENGINE_by_id failed (crypto failure)
Jan  3 14:08:51 wifi1 named[5510]: error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:233:
Jan  3 14:08:51 wifi1 named[5510]: error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:eng_dyn.c:467:
Jan  3 14:08:51 wifi1 named[5510]: error:2606A074:engine routines:ENGINE_by_id:no such engine:eng_list.c:390:id=gost

Is  possible to compile it "--without-gost"?
Or is there any workaround to run bind?
Thanks

**Comment by dduck669** [comment]
I tried to compile it without libgost, but I get the same error. Any suggestion? Maybe it is an OpenSSL problem?
Thank you

**Comment by alllexx88** [comment]
@dduck669 Should be fixed now. Please test

**Comment by dduck669** [comment]
Hi,

I updated bind and related dependencies, but, when I start it, it fails again. The log says:
Jan  5 15:14:11 wifi1 named[2887]: ifiter_ioctl.c:445: INSIST(iter->pos < (unsig                                                                                        ned int) iter->ifc.ifc_len) failed
Jan  5 15:14:11 wifi1 named[2887]: exiting (due to assertion failure)

Please let me kwow, regards

**Comment by alllexx88** [comment]
@dduck669 `bind` works fine for me on a TomatoUSB ARM firmware (Shibby mod). What firmware are you running? I googled your error up, and found [this](https://www.dd-wrt.com/phpBB2/viewtopic.php?p=441291) thread on dd-wrt forums. Though largely outdated, it gives some hints: looks like this error indicates some incompatibility between your kernel and the toolchain used to build `bind`

**Comment by dduck669** [comment]
I use DD-WRT, maybe it's the problem. I'll try tomato and I will let you know. Thank you

**Comment by alllexx88** [comment]
@dduck669 OK, thanks, just note that you have to stop dnsmasq before launching bind (see [here](http://tomatousb.org/forum/t-455435/disable-dnsmasq))

**Comment by dduck669** [comment]
I compiled from source using these options and now named work fine:
./configure --enable-shared --enable-static --with-randomdev="/dev/urandom" --disable-threads --disable-linux-caps --with-libtool --without-lmdb --enable-epoll=yes --with-gost=no --with-gssapi=no --with-ecdsa=no --with-readline=no --sysconfdir=/opt/etc/named --enable-filter-aaaa --without-openssl --disable-symtable

**Comment by alllexx88** [comment]
@dduck669 Sorry for my late response. Have you tried to compile `bind` from source with Optware-ng config? Something like this:

```
		--enable-epoll \
		--prefix=\opt \
		--with-libtool \
		--with-openssl=/opt \
		--with-ecdsa \
		--with-gost \
		--without-libxml2 \
		--sysconfdir=/opt/etc/named \
		--localstatedir=/opt/var \
		--with-randomdev=/dev/random \
		--disable-getifaddrs \
		--enable-filter-aaaa
```

I'm asking since I'm interesting to know if the error you were facing is due to cross-compilation, or whether it's due to some configure option. Thanks
