### ISSUE TITLE
unfs3

### ISSUE THREAD

**Issue by dduck669** [Optware/Optware-ng#247]
Hi, I already installed unfs3, but it fails to start. I think it has library dependencies problem (may be it need to be updated)

Thank you

**Comment by alllexx88** [comment]
Hi,
`unfs3` is **very** old (0.9.22 released on 2009-01-05), and isn't recommended. Did you try to use `nfs-utils` instead?

**Comment by dduck669** [comment]
I can't find it...

**Comment by alllexx88** [comment]
@dduck669 You're right, `nfs-utils` needs fixig/upgrading. I'll look into it

**Comment by alllexx88** [comment]
@dduck669 `nfs-utils` is now available for `uclibc` targets. Note that it depends on **nfsd** kernel module

**Comment by alllexx88** [comment]
Closing due to no response.
