### ISSUE TITLE
SoftEther

### ISSUE THREAD

**Issue by steom** [Optware/Optware-ng#25]
package request:
https://github.com/SoftEtherVPN/SoftEtherVPN/

**Comment by steom** [comment]
OMG!
 sshfs has higher priority than softether!!! 😑😑
😁😁

**Comment by alllexx88** [comment]
`sshfs` was easier to add, since it's more cross-compilation-friendly, and uses a more standard build system. I've added `softethervpn` package, but it (as well as `sshfs`) won't get online until the server gets more free space: it's currently all used up. Hope it'll get sorted out soon.

**Comment by steom** [comment]
thanks... good news!

**Comment by alllexx88** [comment]
`softethervpn` is now in the feeds
