### ISSUE TITLE
dnsmasq /lib linkage 

### ISSUE THREAD

**Issue by juliaplayrix** [Optware/Optware-ng#265]
dnsmasq fails to start with error:

~ # /opt/sbin/dnsmasq --test
libc.so.1: aborted attempt to load /opt/sbin/dnsmasq!

As far as i see it compiled with /lib linkage:
~ # ldd /opt/sbin/dnsmasq
        libc.so.1 => not found
        ld-uClibc.so.0 => /lib/ld-uClibc.so.0 (0x2aaa8000)

Is it possible to change this to /opt/lib?
Thanks.

**Comment by alllexx88** [comment]
Fixed binaries should soon be online (version `2.78-1`)
