### ISSUE TITLE
[request] Gerbera DLNA Server

### ISSUE THREAD

**Issue by dduck669** [Optware/Optware-ng#266]
Can you please build package for Gerbera DLNA Server (https://github.com/gerbera/gerbera)?
Please let me know.
Thank you.

Regards

**Comment by alllexx88** [comment]
I'm currently looking into adding `gerbera` package. I just upgraded `libupnp` to `1.8` branch, a `gerbera` dependency. Now it looks like we're currently missing `duktape` dependency on Optware-ng, and it'd be good to package `libuuid` separately, to not have `gerbera` depend on entire `util-linux`.

**Comment by alllexx88** [comment]
`gerbera` package added:

```
ipkg update
ipkg install gerbera
### start/stop/check status with th rc script:
/opt/etc/init.d/S98gerbera start
/opt/etc/init.d/S98gerbera status
/opt/etc/init.d/S98gerbera stop
/opt/etc/init.d/S98gerbera status
```
