### ISSUE TITLE
HPLIP not working.

### ISSUE THREAD

**Issue by bennyente** [Optware/Optware-ng#269]
Hi, please may update hplip package to latest version? thanks. the current package not working. This is the problem when execute "hp-setup".

/opt/bin/python2.7: symbol 'cupsLangEncoding': can't resolve symbol

/opt/bin/python2.7: symbol 'ippDelete': can't resolve symbol

/opt/bin/python2.7: symbol 'ippFirstAttribute': can't resolve symbol

/opt/bin/python2.7: symbol 'cupsSetUser': can't resolve symbol

/opt/bin/python2.7: symbol 'ippGetInteger': can't resolve symbol

/opt/bin/python2.7: symbol 'ippNew': can't resolve symbol

/opt/bin/python2.7: symbol 'ippGetBoolean': can't resolve symbol

/opt/bin/python2.7: symbol 'ippReadIO': can't resolve symbol

/opt/bin/python2.7: symbol 'cupsServer': can't resolve symbol

/opt/bin/python2.7: symbol 'ippGetValueTag': can't resolve symbol

/opt/bin/python2.7: symbol 'cupsLastError': can't resolve symbol

/opt/bin/python2.7: symbol 'ippSetVersion': can't resolve symbol

/opt/bin/python2.7: symbol 'ippGetName': can't resolve symbol

/opt/bin/python2.7: symbol 'cupsLangDefault': can't resolve symbol

/opt/bin/python2.7: symbol 'ippGetString': can't resolve symbol

/opt/bin/python2.7: symbol 'httpConnectEncrypt': can't resolve symbol

/opt/bin/python2.7: symbol 'ippSetOperation': can't resolve symbol

/opt/bin/python2.7: symbol 'ippAddBoolean': can't resolve symbol

/opt/bin/python2.7: symbol 'cupsDoRequest': can't resolve symbol

/opt/bin/python2.7: symbol 'cupsDoFileRequest': can't resolve symbol

/opt/bin/python2.7: symbol 'ippAddInteger': can't resolve symbol

/opt/bin/python2.7: symbol 'ippSetRequestId': can't resolve symbol

/opt/bin/python2.7: symbol 'ippGetGroupTag': can't resolve symbol

/opt/bin/python2.7: symbol 'ippGetStatusCode': can't resolve symbol

/opt/bin/python2.7: symbol 'ippPort': can't resolve symbol

/opt/bin/python2.7: symbol 'cupsEncryption': can't resolve symbol

/opt/bin/python2.7: symbol 'ippNextAttribute': can't resolve symbol

/opt/bin/python2.7: symbol 'cupsUser': can't resolve symbol

/opt/bin/python2.7: symbol 'ippNewRequest': can't resolve symbol

/opt/bin/python2.7: symbol 'ippErrorString': can't resolve symbol

/opt/bin/python2.7: symbol 'ippAddStrings': can't resolve symbol

/opt/bin/python2.7: symbol 'ippAddString': can't resolve symbol

/opt/bin/python2.7: symbol 'ippWriteIO': can't resolve symbol

/opt/bin/python2.7: symbol 'httpClose': can't resolve symbol
Traceback (most recent call last):
  File "/opt/bin/hp-setup", line 48, in <module>
    from base import device, utils, tui, models, module, services, os_utils
  File "/opt/share/hplip/base/device.py", line 42, in <module>
    from . import status
  File "/opt/share/hplip/base/status.py", line 33, in <module>
    import cupsext
ImportError: unknown dlopen() error

thanks a lot, bye.

**Comment by alllexx88** [comment]
I've upgraded `hplip` to latest (3.17.11), used patches from Entware-ng and some other fixes. `hp-setup` seem to work now, but I don't owe a compatible device to test fully.

```
# hp-setup
warning: python-dbus not installed.

HP Linux Imaging and Printing System (ver. 0.0.0)
Printer/Fax Setup Utility ver. 9.0

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

(Note: Defaults for each question are maked with a '*'. Press <enter> to accept the default.)


Using connection type: usb


error: No device selected/specified or that supports this functionality.                                                                                                                                                                                                      
```

**Comment by bennyente** [comment]
Thanks,

Now hp-setup working and I have the same result you post.
Maybe is necessary to add py27-dbus-python package because the tool work on Python 2.7 version.

thanks.

**Comment by alllexx88** [comment]
I doubt that adding `dbus-python` for `python27` will help here. Anyways, I did add it, so you can try it:
```
ipkg update
ipkg install py27-dbus-python
```

**Comment by bennyente** [comment]
Well, the py27-dbus-python resolve the WARNING python-dbus not installed.
hp-setup scripts need these symlink to work properly. I've added the commands on startup script in my router.
ln -s /opt/etc/hp /etc/hp
ln -s /opt/etc/cups /etc/cups

So hp-setup added my HP printer to Cups server. The HPLIP driver needed for ignoring low ink warning in cups.

Now I have a working cups server that export an Airplay compatible printer. :-)

Thanks.

**Comment by alllexx88** [comment]
That's good news 😄 
I've patched `hplip` package to use optware paths. Can you please test if `hp-setup` works without those `/etc` symlinks?

**Comment by bennyente** [comment]
Tested and working fine. Thanks.

**Comment by alllexx88** [comment]
Great. Thanks for testing, closing the issue.
