### ISSUE TITLE
[Package request] imagemagick for php

### ISSUE THREAD

**Issue by me11ved** [Optware/Optware-ng#271]
Hi Alex!
Please add an imagemagick package for php

**Comment by alllexx88** [comment]
`php-imagick` package added. Have fun 😄

**Comment by me11ved** [comment]
Hi Alex!
I'm sorry for the trouble, but I'm having problems

```
- ipkg update
- ipkg upgrade

- ipkg list php-* - no results php-imagick :(

```

**Comment by alllexx88** [comment]
@me11ved Sorry, looks like problems with Jenkins builder 😞 Which feed do you use? I can make a manual build for your target and upload the package here...

**Comment by me11ved** [comment]
Ok. I will wait

**Comment by me11ved** [comment]
Hi Alex.

How are things with the package?

**Comment by alllexx88** [comment]
@me11ved There's still something wrong with Jenkins, but `php-imagick` package is uploaded for all feeds now

**Comment by me11ved** [comment]
Hi Alex.

When the Apache is reloaded in the log:
`sbin/apache-httpd: can't resolve symbol 'MagickWandGenesis'`

**Comment by alllexx88** [comment]
@me11ved Fixed now. Please upgrade `php-imagick` to `3.4.3-2`

**Comment by me11ved** [comment]
I reloaded the apache and started testing.
php does not see this class.
Error:
`Fatal error: Class 'Imagick' not found`

Apache error:
`PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'imagick.so' in Unknown on line 0`

**Comment by alllexx88** [comment]
I'm not seeing this on my side. Tested on `buildroot-i686` and `buildroot-armeabi-ng` (softfloat ARMv7). I first verified that `phpinfo();` reports that `imagick module` works fine. I also created a thumbnail generating page using `Imagick` class (like one from [PHP site imagick examples](http://php.net/manual/en/imagick.examples-1.php)), and it creates thumbnails fine.

Maybe, you had a short write when installing `php-imagick` package, or some issues with the fs? Does `/opt/bin/php -m` report any issue with loading `imagick` module?

**Comment by me11ved** [comment]
Hi Alex.

`/opt/bin/php -m`

`PHP Startup: Unable to load dynamic library '/opt/lib/php/extensions/imagick.so' - File not found in Unknown on line 0
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'imagick.so' in Unknown on line 0`

`ls -s /opt/lib/php/extensions/imagick.so`
`312 /opt/lib/php/extensions/imagick.so`

**Comment by alllexx88** [comment]
Hm, doesn't look like a short write (you're using `buildroot-armeabi-ng` feed, correct?):

```
[root@unknown root]$ ls -s /opt/lib/php/extensions/imagick.so
   312 /opt/lib/php/extensions/imagick.so
[root@unknown root]$ /opt/bin/php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
date
dba
dom
ereg
exif
fileinfo
filter
ftp
hash
imagick
json
libxml
openssl
pcre
PDO
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlwriter
xsl
zlib

[Zend Modules]
```

Could you first try to reinstall the package with `ipkg -force-reinstall install php-imagick`, and second, run a filesystem check on your drive? I remember I had strange issues with a failing pen drive once...

**Comment by me11ved** [comment]
Hi Alex.
A library is not required. Thank you.
