### ISSUE TITLE
[Request] Csync2

### ISSUE THREAD

**Issue by dduck669** [Optware/Optware-ng#273]
Can you please build package for Csync2. Source are available at http://oss.linbit.com/csync2/.
Thank you,

Regards.

**Comment by alllexx88** [comment]
Done: 5f18d70a7b01662d2cef48c827a367070be90852 Please test and report back 😃

**Comment by dduck669** [comment]
Ok, sorry for delay, but I was very busy during these days. It's good, thanks!!!
