### ISSUE TITLE
installing dovecot not working giving error

### ISSUE THREAD

**Issue by cypriotxx** [Optware/Optware-ng#277]
hi there 
i have a TS-459 with latest firmware 4.3 

i have installed Optware-ng without an error 
but when i try this

[/opt] # /opt/bin/ipkg install dovecot
Installing dovecot (1.2.0.beta1-4) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/ ... 4_i686.ipk.
Installing openssl (1.0.2n-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/ ... 1_i686.ipk.
Installing cacerts (20180223-1) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/ ... 1_i686.ipk.
Configuring cacerts.
Configuring openssl.
Configuring dovecot.
/opt/sbin/dovecot: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
Collected errors:
* pkg_run_script: package "dovecot" postinst script returned status 127.
* opkg_configure: dovecot.postinst returned 127.

what can i do to fix this please

**Comment by alllexx88** [comment]
Hi,
Thanks for the report. It's a dependency bug: `dovecot` depends on `libcap`.

**Comment by cypriotxx** [comment]
yes i now installed libcap as well and got this error ahh
i did chmod but still the same error  

[/opt] # /opt/sbin/dovecot
Fatal: safe_mkdir() failed: /opt/var/run/dovecot/login (40777) is still not mode 750
[/opt] #

**Comment by alllexx88** [comment]
Hm, I'm not seeing this on my side. You did a `chmod 750 /opt/var/run/dovecot/login`, right? What is the output of:
```
ls -d -l /opt/var/run/dovecot/login
```
?

**Comment by cypriotxx** [comment]
[/] #  chmod 750 /opt/var/run/dovecot/login
[/] # /opt/sbin/dovecot
Fatal: safe_mkdir() failed: /opt/var/run/dovecot/login (40777) is still not mode 750
[/] # ls -d -l /opt/var/run/dovecot/login
drwxrwxrwx    1 admin    administ         0 Mar  1 17:25 /opt/var/run/dovecot/login/
[/] #

would it help to check via teamviewer .. ?

**Comment by alllexx88** [comment]
```
[/] # chmod 750 /opt/var/run/dovecot/login
...
[/] # ls -d -l /opt/var/run/dovecot/login
drwxrwxrwx 1 admin administ 0 Mar 1 17:25 /opt/var/run/dovecot/login/
```

So `chmod` fails. Do you perhaps have `/opt` on a fat32 filesystem, which doesn't support permissions? No other reason I can think of for this to happen 😕

**Comment by cypriotxx** [comment]
ahh i dont know about that ,  what command would show that ?

**Comment by alllexx88** [comment]
`df -T` shows all filesystems,
`ls -d -l /opt` -- this shows if `/opt` is a symlink to somewhere
`mount | grep /opt` -- in case `/opt` is a separate mount (e.g., a bind mount)

**Comment by cypriotxx** [comment]
[/] # df -T
df: invalid option -- T
BusyBox v1.01 (2017.12.07-18:28+0000) multi-call binary

Usage: df [-hmkc] [FILESYSTEM ...]

Print the filesystem space used and space available.

Options:
        -c      correct formatting error

        -h      print sizes in human readable format (e.g., 1K 243M 2G )
        -m      print sizes in megabytes
        -k      print sizes in kilobytes(default)

[/] # ls -d -l /opt
drwxrwxrwx    1 admin    administ      4096 Mar  2 09:50 /opt/
[/] # mount | grep /opt
/dev/sds2 on /opt type fuseblk (rw,allow_other,blksize=4096)
[/] #

**Comment by alllexx88** [comment]
> [/] # mount | grep /opt
> /dev/sds2 on /opt type fuseblk (rw,allow_other,blksize=4096)

Here's the answer. You're most likely using an NTFS partition, which doesn't support file permissions 😸 You should format it to some filesystem that supports them: ext2/ext3/ext3...

**Comment by cypriotxx** [comment]
ahh :dancer: 
thank you so much for helping out 
i have no idea how to do that but will see what i can find online .. :+1:
