### ISSUE TITLE
Mail packages - please update if possible

### ISSUE THREAD

**Issue by Amp3rwater** [Optware/Optware-ng#278]
I tried to configure sendmail to be able to send some info when necessary. Here is what I found:
- sendmail: binary is missing, sendmail does not contain it, sendmail-bin is not available (I know there is busybox one)
- putmail: does not satisfy_dependencies_for: py-putmail-common
- msmtp: can't load library 'libgnutls.so.28'

I finally managed to run msmtp changing name of 'libgnutls.so.30' but would be nice to have them all available and ready to use.

Relayed to : ARMv7 EABI softfloat

**Comment by alllexx88** [comment]
Thanks for the report. `sendmail`, `msmtp` and `putmail` should be fixed now.

**Comment by Amp3rwater** [comment]
Thank you for quick response.
