### ISSUE TITLE
build error in pycurl?

### ISSUE THREAD

**Issue by Lalarian** [Optware/Optware-ng#280]
Hello!
I'm using pyload on my router, installed through optware-ng.
Since a few weeks pyload doesn't start anymore, throwing the error:

> ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)

Regarding to the error message, I think that py27-curl has been built using wrong parameters?
Thank you! :)

**Comment by alllexx88** [comment]
Hi,

There was such an issue with `py27-curl`, version `7.21.5-5` (see #274). It's fixed in the current `7.21.5-6` version, so I assume that you just need to upgrade `py27-curl`.

**Comment by Lalarian** [comment]
I did successfully
"ipkg update"
and
'ipkg upgrade"

Isn't this enough?

**Comment by Lalarian** [comment]
Well.. I don't even know why.. but I got it working now.
I did some ldd for checking the dependencies of pycurl.so
libssl was listed there, but still I manually deleted the file from site-packages.
Then I uninstalled and installed py27-curl (like dozens of times before..) and - it's working ...
