### ISSUE TITLE
Collectd missing libtool dependency

### ISSUE THREAD

**Issue by AloysAugustin** [Optware/Optware-ng#281]
Launching a freshly installed collectd ( version`collectd - 5.2.1-4`) fails with the following error:
```
# /opt/sbin/collectd -C /opt/etc/collectd.conf -f
/opt/sbin/collectd: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
```
This is very similar to #88, and manually installing `libtool` immediately resolves the issue.

**Comment by alllexx88** [comment]
Thanks for the report 😃

**Comment by AloysAugustin** [comment]
Thanks for the super fast fix!
