### ISSUE TITLE
python 3.5.4  Segmentation fault

### ISSUE THREAD

**Issue by xylake** [Optware/Optware-ng#283]
a recent update to python 3.5.4 leads to pip3 Segmentation fault

$ /opt/local/bin/pip3
Segmentation fault

**Comment by xylake** [comment]
It doesn't work even after update to 10.0.0.

$ ipkg list-installed | grep py
py3-ipython - 3.1.0-3
py3-pip - 10.0.0-1
py3-setuptools - 12.0.1-3
python3 - 3.5.4-1

$ /opt/bin/pip3
Segmentation fault

BTW there is a link error for ipython,
$ /opt/bin/ipython
-bash: /opt/bin/ipython: /home/jenkins/Optware-ng/buildroot-armeabihf/host/staging/opt/bin/python3.5: bad interpreter: No such file or directory

 and after fixing the link also a segfault occurs.
$ /opt/bin/ipython
Segmentation fault

**Comment by alllexx88** [comment]
This should be fixed now after `python3` package major upgrade to 3.7.1. Please test if you're still with me :smile:
