### ISSUE TITLE
Cannot resolve ipkg.nslu2-linux.org domain anymore??

### ISSUE THREAD

**Issue by BalaWxd** [Optware/Optware-ng#293]
When running ipkg update, finds ipkg.nslu2-linux.org domain name records don't exist. What a replacement solution will there be?

**Comment by mitzone** [comment]
Hello,
Same issue here. 
Thanks.

**Comment by BalaWxd** [comment]
Just realized the entware can replace optware and uses opkg to install package.

**Comment by satfreak** [comment]
Same here feed is gone, and also the website http://ipkg.nslu2-linux.org.

Strange where did it go ?

**Comment by mitzone** [comment]
The domain nslu2-linux.org is in **autoRenewPeriod**  status at godaddy. It exired on August 19th. Hope they will renew it.

**Comment by ElTopo** [comment]
@BalaWxd Last time I checked, entware-ng didn't even have gcc package.

**Comment by ledzep2** [comment]
Does anyone know the server ip the domain previously resolved to? Or is the server gone too?

**Comment by alllexx88** [comment]
Sorry for the delayed answer. There's some maintenance being done on nslu2-linux resources. Expected to be up ~ on Aug 28th.

**Comment by johnRambo2k14** [comment]
So there is no temporary of backup endpoints we can use?

**Comment by alllexx88** [comment]
@johnRambo2k14 Unfortunately, currently there're no official mirrors. Fortunately though, `nslu2-linux.org` server is highly reliable, and has a close to 100% uptime. btw, it's up now 😃
