### ISSUE TITLE
Can't install node:

### ISSUE THREAD

**Issue by PrecociouslyDigital** [Optware/Optware-ng#303]
Hi, I just installed optware (legacy armv5) and I'm having trouble running node; optware installs it fine, but when I try to run node I get the error `/opt/bin/node: can't load library 'libdl.so.1'`; I see that this was also an issue in #221 but thought that all packages had been rebuilt to use libc.so.1; If not, how can I fix this issue?

**Comment by alllexx88** [comment]
Hi. There was a typo in `node010` makefile, due to which both `node010_0.10.48-1_arm.ipk` (an old broken one) and `node010_0.10.48-2_arm.ipk` (the proper one) got to the feed, and only the older ones get indexed in such cases. It'll be fine soon, when the feed updates.
