### ISSUE TITLE
madam: can't resolve symbol 'gnu_dev_major'

### ISSUE THREAD

**Issue by doom1942** [Optware/Optware-ng#307]
Getting mdadm: can't resolve symbol 'gnu_dev_major'

When trying to run a command 'mdadm --assemble --scan'

Furthermore, received an error when trying to creat the array as well.

mdadm: /dev/sda appears to contain an ext2fs file system
    size=7864320K  mtime=Sat Dec  1 14:18:36 2018
mdadm: /dev/sdb appears to contain an ext2fs file system
    size=7811072K  mtime=Sat Dec  1 14:18:36 2018
mdadm: /dev/sdc appears to contain an ext2fs file system
    size=15642624K  mtime=Sat Dec  1 14:18:36 2018
mdadm: /dev/sdd2 appears to contain an ext2fs file system
    size=60956636K  mtime=Sat Dec  1 14:18:37 2018
Continue creating array? y
mdadm: can't resolve symbol '__ctype_b_loc'

on MIPSEL

**Comment by alllexx88** [comment]
Thanks for the report. As the commit says, it should be fixed now. Just wait a while until the feed is upgraded.
