### ISSUE TITLE
Samba 3 load library error with Arm5 legacy

### ISSUE THREAD

**Issue by DrPeterVC** [Optware/Optware-ng#308]
I recently updated from optware to optwage ng on my WD My Book World II (aka White light).  Unfortunately I seem to be unable to run Samba 3 (Samba 2 works OK). 

~ # ipkg install samba36
Installing samba36 (3.6.24-2) on /opt/.
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/samba36_3.6.24-2_arm.ipk.
Configuring samba36.
.....
~ # testparm
/opt/bin/testparm: can't load library 'libpthread.so.1'

And when I try to restart samba:

/etc/init.d/S90smbd restart
Restarting SMB services:
Shutting down SMB services: OK
Shutting down NMB services: OK
Starting SMB services: /opt/sbin/smbd: can't load library 'libpthread.so.1'
FAIL
Starting NMB services: /opt/sbin/nmbd: can't load library 'libpthread.so.1'
OK
done.

Any ideas?

**Comment by alllexx88** [comment]
Fixed now. Either wait for the feed to update, or install the proper version manually (it was there in the feed, just not indexed):
```
ipkg install http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/samba36_3.6.24-3_arm.ipk
```

**Comment by DrPeterVC** [comment]
~ # ipkg install http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/samba36_3.6.24-3_arm.ipk
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/samba36_3.6.24-3_arm.ipk.
Collected errors:
 * opkg_download: Failed to download http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng-legacy/samba36_3.6.24-3_arm.ipk, wget returned 8.
~ #

**Comment by alllexx88** [comment]
Yeah, manual download of `3.6.24-3` version won't work now: I fixed a dependency bug in `samba36`, so current version in the feed is `3.6.24-4`, hence the older `3.6.24-3` version I referenced is moved to archive :smile:
