### ISSUE TITLE
PHP issues?

### ISSUE THREAD

**Issue by steom** [Optware/Optware-ng#35]
PHP Fatal error:  Call to undefined function in imap_open() imap-move.php 

https://github.com/edoceo/imap-move
http://edoceo.com/creo/imap-move

**Comment by alllexx88** [comment]
This should be fixed by installing `php-imap` package

**Comment by steom** [comment]
not work

php ./imap-move.php --fake -s imap-ssl://username@gmail.com:password@imap.gmail.com:993/

waiting for OFFLINEIMAP to try with that
