### ISSUE TITLE
Can SSLH be added?

### ISSUE THREAD

**Issue by L3rd** [Optware/Optware-ng#45]
Can SSLH be added (http://www.rutschle.net/tech/sslh.shtml)?

FYI, It is already present in Entware so I believe it is feasible.

**Comment by alllexx88** [comment]
Sorry for my late response, I'll look into copying it from Entware. Now that I'm done with fixing openjdk8, I'll start sorting out package requests

**Comment by alllexx88** [comment]
`sslh` package added. Unlike Entware-ng package, it's built with config file support and regex probes

**Comment by L3rd** [comment]
Thanks!
