### ISSUE TITLE
samba server on android

### ISSUE THREAD

**Issue by armando-basile** [Optware/Optware-ng#48]
Hi,
i tryed to use package samba to share on my network my usb hd connected to my box android with optware.
There are some problems related to android user management that is not equal to linux, i think similar to dropbear (you released infact specific package dropbear-android)

is there a workaround ?

**Comment by alllexx88** [comment]
I believe, the easiest workaround is to create `/etc/passwd`: it helped me to get `openssh-sftp-server` to work

**Comment by armando-basile** [comment]
Could you post a sample of passwd file that could be ok on an android box with optware-ng ?
i tryed without success

**Comment by alllexx88** [comment]
Hi,
Sorry for my late response. I'm quite busy recently, as you can tell from my low activity. Some while ago I posted some CWM flashables on xda, and got zero response, which means there's no interest for Optware-ng on android, so this isn't something that's being worked on by me, but you can still try it:
http://forum.xda-developers.com/android/development/cwm-t3237933
Apart from else, it also creates `/etc/passwd` file with `root` entry: this is what made `openssh-sftp-server` to work

**Comment by armando-basile** [comment]
ok, it work :)

- remounted /system with read-write permissions
```
# mount -o remount,rw /system
```
- created /etc/passwd with 2 users:
```
root:x:0:0:root:/data/opt:/bin/bash
nobody:x:1005:1005:nobody:/data/opt:/bin/bash
```
- installed avahi
```
# ipkg install avahi
```
- create samba users:
```
# smbpasswd -a nobody (with empty password)
# smbpasswd -a root (with a real password)
```
- modified /opt/etc/samba/smb.conf:
```
[share]
    path = /storage/external_storage/sda1
    read only = no
    valid users = root
    write list = root
    guest ok = no
```
- remounted /system with read-only
```
# mount -o remount,ro /system
```
- launch samba service
```
# /opt/etc/init.d/S08samba restart
```
