### ISSUE TITLE
Request for PHP module for caching in Owncloud (APCu or memcached)

### ISSUE THREAD

**Issue by kariburger** [Optware/Optware-ng#50]
Hi,
after some trouble I got my Tomato Router (Asus RT-N16) to run with lighttpd and Owncloud. My main problem was, that I had to add the call "/usr/sbin/php-cgi -a -b 127.0.0.1:9000" to the init-script-calls in the GUI, so that php-fcgi startet to work.

Now I would like to enhance the speed of Owncloud with the help of caching (see [https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/caching_configuration.html](https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/caching_configuration.html) ).

But sadly none of the supported cache engines is available in optware-ng. I tried to install the "memcached" package - but that is not enough, as the corresponding php-plugin is missing.

Thanks,
Achim

**Comment by alllexx88** [comment]
@kariburger I don't know if you're still interested in this, but I just added `php-memcached` package. Please test it if you can. Thanks
