### ISSUE TITLE
Serveral Python modules reqest

### ISSUE THREAD

**Issue by md2k** [Optware/Optware-ng#51]
Hi, it is possible to add for python 2.7 few modules?

Jinja2 (https://pypi.python.org/pypi/Jinja2)
lxml (https://pypi.python.org/pypi/lxml/3.5.0)
requests (https://pypi.python.org/pypi/requests)
tornado (https://pypi.python.org/pypi/tornado)
and lates pycurl

i hope that this not very big request, thank you in advance :)

**Comment by alllexx88** [comment]
@md2k done: see 6784733ce8b0c60de60dc89b531f2c9b34096dae ee1d10d7d2027bc061233461ede05a8fc39044ab ee1d10d7d2027bc061233461ede05a8fc39044ab 5e0441635ff20a5a606174883ff630cd2771b6db 45d8f5b28ab18f07f21c38eeab070b8f0ef32fbb c46a749a27a639052fece67489b23b7d3f4a0a2c 980f6a894d3febbcd383d0ce47a0a97351792b16 eaa2d91e28521acd6c77861624759690a333fd9e
Building at this very moment: see http://jenkins.nas-admin.org/view/Optware/

**Comment by md2k** [comment]
Thank you , going to try them as soon as possible

**Comment by alllexx88** [comment]
@md2k closing for now, if you have issues, reopen
