### ISSUE TITLE
Transmission - 2.84-2 crash

### ISSUE THREAD

**Issue by TeHashX** [Optware/Optware-ng#53]
Hi, after adding a torrent file, transmission crashes without any log notice, I set message-level to 3 which is debug, but still nothing.
RT-AC66U router, latest RMerlin firmware v380.57

**Comment by TeHashX** [comment]
I get a lot of reports on hqt.ro about transmission, deluge, pyload... I think is since you updated uclibc-ng

**Comment by alllexx88** [comment]
Hi, I plan to rebuild buildroot-mipsel-ng feed with 2.6.22.19 kernel headers, which match RT-N66U linux kernel version. Currently I faced many issues due to toolchain built with kernel headers newer that end system uses. Firmwares that use newer kernels will still work OK. Also, if there're some incompatibilities between recent uClibc-ng upgrades, full rebuild will also fix this.

**Comment by sphinctor** [comment]
I'm having the very same issues, Transmission daemon stops after a few mins of downloading torrents. Am using Asus RT-N66U.

Copy/past below from terminal...


admin@RT-N66U-D210:/tmp/mnt/SphinxHDD/optware-ng# uname -a
Linux RT-N66U-D210 2.6.22.19 #1 Thu Dec 24 13:53:52 EST 2015 mips GNU/Linux
admin@RT-N66U-D210:/tmp/mnt/SphinxHDD/optware-ng# mount
rootfs on / type rootfs (rw)
/dev/root on / type squashfs (ro)
proc on /proc type proc (rw)
tmpfs on /tmp type tmpfs (rw)
devfs on /dev type tmpfs (rw,noatime)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw)
/dev/mtdblock4 on /jffs type jffs2 (rw,noatime)
usbfs on /proc/bus/usb type usbfs (rw)
/dev/sdb5 on /tmp/mnt/SphinxHDD type ext3 (rw,nodev,noatime,data=ordered)
admin@RT-N66U-D210:/tmp/mnt/SphinxHDD/optware-ng# df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/root                20736     20736         0 100% /
tmpfs                   119836       876    118960   1% /tmp
devfs                   119836         0    119836   0% /dev
/dev/mtdblock4           10240       568      9672   6% /jffs
/dev/sdb5            1915794524 403973016 1414147920  22% /tmp/mnt/SphinxHDD
admin@RT-N66U-D210:/tmp/mnt/SphinxHDD/optware-ng# free
             total         used         free       shared      buffers
Mem:        239672       131652       108020            0         4080
-/+ buffers:             127572       112100
Swap:       524280          676       523604

**Comment by alllexx88** [comment]
Just to keep you updated, the feed is currently being rebuilt with new linux-2.6.22.19 toolchain. It takes some time, and I also have to fix some compilation errors along tha way, since some kernel features present in 2.6.36.4 kernel (version used by previous toolchain) aren't available in 2.6.22.19. I already confirmed that issues I had with gdb are gone, and, I hope, many other issue will be gone too. So please stay tuned

**Comment by alllexx88** [comment]
@TeHashX @sphinctor recompiled feed is now online. Reinstall all currently installed packages with:

```
ipkg update
ipkg -force-reinstall install `ipkg list_installed|cut -d ' ' -f1`
```

Please test and report back

**Comment by truwa** [comment]
Hi allexx88. I have asus N66 and I am having the same problem. Transmission crashes in a couple of minutes if there is an active torrent, no log messages.Reinstalling all the packages did not solve the problem.

**Comment by sphinctor** [comment]
Thanks alllexx88.

I ran the update without issues, however seems the force reinstall has given me the following error and am afraid was not completed successfully.I tried running the transmission daemon, however continues to crash after 2-3 minutes... any thoughts?

Copy/paste from the terminal below...

admin@RT-N66U-D210:/tmp/mnt/SphinxHDD/optware-ng# ipkg -force-reinstall install
`ipkg list_installed|cut -d ' ' -f1`
Reinstalling findutils (4.2.32-1) on /opt/...
Downloading http://optware-ng.zyxmon.org/buildroot-mipsel-ng/findutils_4.2.32-1_mipsel.ipk
Reinstalling libnsl (1.0.12-1) on /opt/...
Downloading http://optware-ng.zyxmon.org/buildroot-mipsel-ng/libnsl_1.0.12-1_mipsel.ipk
Reinstalling uclibc-opt (1.0.12-1) on /opt/...
Downloading http://optware-ng.zyxmon.org/buildroot-mipsel-ng/uclibc-opt_1.0.12-1_mipsel.ipk
Configuring findutils
update-alternatives: Linking //opt/bin/find to /opt/bin/findutils-find
update-alternatives: Linking //opt/bin/xargs to /opt/bin/findutils-xargs
Configuring libnsl
Configuring uclibc-opt
An error ocurred, return value: 4.
Collected errors:
Cannot find package Successfully.
Check the spelling or perhaps run 'ipkg update'

**Comment by alllexx88** [comment]
I confirm this issue, this happens with uclibc-ng 1.0.10-1.0.12. If I downgrade to 1.0.9, it works OK. I've written to uclibc-ng mailing list, and I hope the solution will come soon. For now, you can manually downgrade it:

```
# comment out current ipk src feed:
sed -i -e '/src\/gz alllexx/s/^/#/' /opt/etc/ipkg.conf
# remove current uclibc-ng
ipkg update
ipkg -force-depends remove uclibc-opt
# install old uclibc-ng:
ipkg install http://optware-ng.zyxmon.org/buildroot-mipsel-ng.old/uclibc-opt_1.0.9-2_mipsel.ipk
# hold old version for now
# (so it's not automatically upgraded when you run `ipkg upgrade`)
ipkg flag hold uclibc-opt
# uncomment ipk src feed:
sed -i -e '/src\/gz alllexx/s/^#//' /opt/etc/ipkg.conf
ipkg update
```

Later, after fix arrives, do this:

```
ipkg flag installed uclibc-opt
ipkg update
ipkg upgrade
```

**Comment by alllexx88** [comment]
Please test and reopen if not fixed

**Comment by sphinctor** [comment]
Thanks again alllexx88 - looks like your workaround has solved the issue! I downgraded as per your instructions without any issues. I'm please to let you know that I've been running the daemon for about an hour now and has not crashed. This appears to have resolved the problem, thanks again for your help with this!

**Comment by alllexx88** [comment]
@sphinctor Please try the latest uclibc-ng package update:

```
ipkg flag installed uclibc-opt
ipkg update
ipkg upgrade
```

Thanks to swift response by Leonid Lisovskiy on uclibc-ng mailing list (se [here](http://mailman.uclibc-ng.org/pipermail/devel/2016-February/000744.html)), the culprit commit was [found](http://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/commit/?id=2636b17616). I added uclibc-ng patch to revert this commit, and currently it's working OK on my test machine.

**Comment by Bobbar** [comment]
@alllexx88 @TeHashX 

I've been following this as well. I updated the uclibc package as per the instructions and transmission is working much better now.

Thank you everyone!

**Comment by alllexx88** [comment]
@Bobbar Thanks for the feedback! deluge and pyload should work OK now as well (I tested deluge-develop --- works fine).

**Comment by TeHashX** [comment]
I don't have a mipsel router anymore to test but thanks for your fixes :+1: 
As soon as finish reinstalling www.hqt.ro I will try to setup plexmediaserver on arm routers, I own a RT-AC68U now
