### ISSUE TITLE
ddclient

### ISSUE THREAD

**Issue by pwallner** [Optware/Optware-ng#58]
Hi,

after starting ddclient I get this error:

    Bareword` "Errno::EINVAL" not allowed while "strict subs" in use at /opt/lib/perl5/5.20.1/armv7l-linux/IO/Socket.pm line 135.
    Compilation failed in require at /opt/sbin/ddclient line 20.
    BEGIN failed--compilation aborted at /opt/sbin/ddclient line 20.

**Comment by alllexx88** [comment]
Hi,

Should be fixed by 1bf60c45f6cf9fe7c712ca30c24b50de1568c371 Sorry for my late response on this.
