### ISSUE TITLE
Status of collectd package?

### ISSUE THREAD

**Issue by tbyehl** [Optware/Optware-ng#59]
I see that collectd was added a while back but never released. Any chance of getting this in the feed?

**Comment by alllexx88** [comment]
I forgot to mention it earlier, but collectd is in the repos for a while now. It's the same version that was added for testing (5.2.1), and I also haven't tested how well it works, I only verified that it starts OK. If you're still interested in this, please have a look.

**Comment by tbyehl** [comment]
Thanks, hopefully I can find some time to mess with it next week.
