### ISSUE TITLE
Request for compile libical - dependency for gnokii

### ISSUE THREAD

**Issue by tomasiek** [Optware/Optware-ng#60]
Please compile and add libical as a dependency for gnokii. Currently gnokii not work without this package . I use libical from repo: http://ipkg.nslu2-linux.org/feeds/optware/oleg/cross/stable/ - but i have to copy it manualy to /opt/lib

**Comment by alllexx88** [comment]
libical is (and always was) available in the feeds. For mipsel it's here: http://ipkg.nslu2-linux.org/optware-ng/buildroot-mipsel-ng/libical_0.48-1_mipsel.ipk
