### ISSUE TITLE
mkvtoolnix is missing icu dependency

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#61]
well, regarding the following messages, I suspect that the missing dependency is libiconv, unfortunatelly, libiconv.ipk doesn't exist for i686 at least.

root@synology:/opt/bin# mkvmerge
mkvmerge: error while loading shared libraries: libicudata.so.56: cannot open shared object file: No such file or directory

root@synology:/opt/bin# ldd mkvmerge | grep not
        libicudata.so.56 => not found
        libicui18n.so.56 => not found
        libicuuc.so.56 => not found

**Comment by alllexx88** [comment]
mkvtoolnix was actually missing icu dependency. Fixed in 8.8.0
