### ISSUE TITLE
util-linux-ng is missing from Packages.gz

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#62]
all is in the title, i686 at leat. regards

Package: util-linux-ng
Version: 2.15-2
Depends: glibc-opt, e2fslibs, ncursesw, zlib, getopt
Status: install user installed
Section: utils
Architecture: i686
maintainer: NSLU2 Linux <nslu2-linux@yahoogroups.com>
MD5Sum: 76f8ce6acfba43f9a737e712c2769997
Size: 530926
Filename: util-linux-ng_2.15-2_i686.ipk
Source: ftp://ftp.kernel.org/pub/linux/utils/util-linux-ng/v2.15/util-linux-ng-2.15.tar.gz
Description: A suite of essential utilities for any Linux system, this version is a fork of util-linux.

**Comment by alllexx88** [comment]
This is intended to be this way: currently, former `util-linux-ng` project is now the official `util-linux`, so `util-linux-ng` package is removed from the repos --- use `util-linux` instead. That `util-linux-ng_2.15-2_i686.ipk` file is left from older builds, and isn't indexed on purpose.
