### ISSUE TITLE
vim is missing gettext dependency

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#63]
all is in the title, i686 at least, regards
also, gexttext seems to be missing a reference to libgnuintl.so.56 (ipkg files)

**Comment by alllexx88** [comment]
gettext dependency fixed, thanks/
What do you mean by "gexttext seems to be missing a reference to libgnuintl.so.56"?

**Comment by gits68** [comment]
arch i686
# ipkg download gettext
# tar xf gettext_0.19.6-1_i686.ipk ./data.tar.gz
# tar vtf data.tar.gz  | grep libgnuintl.so
lrwxrwxrwx root/root         0 2015-10-30 13:48 ./opt/lib/libgnuintl.so -> libgnuintl.so.8.1.4
lrwxrwxrwx root/root         0 2015-10-30 21:52 ./opt/lib/libintl.so -> libgnuintl.so
lrwxrwxrwx root/root         0 2015-10-30 13:48 ./opt/lib/libgnuintl.so.8 -> libgnuintl.so.8.1.4
-rwxrwxr-x root/root     39108 2015-10-30 21:52 ./opt/lib/libgnuintl.so.8.1.4
# grep libgnuintl.so /opt/lib/ipkg/info/gettext.list
<nothing>
