### ISSUE TITLE
man is build againt /lib/ld-linux.so.2 instead of /opt/lib/ld-linux.so.2

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#64]
root@synology:/opt/bin# ldd man
        linux-gate.so.1 =>  (0xf77cb000)
        libc.so.6 => /opt/lib/libc.so.6 (0xf7617000)
        /lib/ld-linux.so.2 (0xf77cc000)

root@synology:/opt/bin# man
Segmentation fault (core dumped)

**Comment by alllexx88** [comment]
Fixed, thanks:

```
DiskStation> ldd /opt/bin/man
        linux-gate.so.1 (0xf77cc000)
        libc.so.6 => /opt/lib/libc.so.6 (0xf7618000)
        /opt/lib/ld-linux.so.2 (0xf77cd000)
```
