### ISSUE TITLE
busy box can't resolve symbol 'mallopt'

### ISSUE THREAD

**Issue by pwallner** [Optware/Optware-ng#65]
I fear something happens on my router, I got this error:

    root@mcpatric:/opt/bin# ./busybox
    /opt/bin/busybox: can't resolve symbol 'mallopt'

This is what ldd writes:

    root@mcpatric:/opt/bin# ldd ./busybox
        libcrypt.so.1 => /opt/lib/libcrypt.so.1 (0x4018b000)
        libm.so.1 => /opt/lib/libm.so.1 (0x40143000)
        libc.so.1 => /opt/lib/libc.so.1 (0x401b2000)
        ld-uClibc.so.1 => /opt/lib/ld-uClibc.so.1 (0x4003f000)

I have a RT-AC68U running Advancedtomato v3.1-132 AIO-64k (equals shibby tomato 132 K26ARM USB AIO-64K)

Thx
Patrick

**Comment by alllexx88** [comment]
I fear this is my fault, while upgrading uclibc-ng to 1.0.11, I switched from MALLOC_STANDARD to MALLOC, as advised bu uclibc-ng developer Waldemar Brodkorb, and I assume that this was a bad idea: the issue you encountered shows that these configs aren't intercompatible. I think, the easiest solution is to switch back to MALLOC_STANDARD, rather than re-compiling entire feed. I'll do this soon, but not for mipsel feed, since it's being under development currently (yours is ARMv7).

**Comment by alllexx88** [comment]
I've upgraded uclibc-ng to 1.0.12 and reverted to MALLOC_STANDARD:

```
root@unknown:/opt# uname -a
Linux unknown 2.6.36.4brcmarm #26 SMP PREEMPT Mon Feb 9 14:40:52 CET 2015 armv7l GNU/Linux
root@unknown:/opt# /opt/bin/busybox
BusyBox v1.23.0 (2015-09-12 13:21:42 EEST) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2012.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        [, [[, acpid, arp, arping, ash, awk, base64, basename, bash, beep, blkid, blockdev, bootchartd, bunzip2, bzcat, bzip2, cal, cat, chattr, chgrp, chmod, chown, chroot, chrt, chvt,
        cksum, clear, cmp, comm, conspy, cp, cpio, cut, date, dd, deallocvt, depmod, devmem, df, dhcprelay, diff, dirname, dmesg, dnsdomainname, dos2unix, du, dumpleases, echo, ed, egrep,
        eject, env, ether-wake, expr, false, fatattr, fbsplash, fdisk, fgconsole, fgrep, find, flock, free, fsck, fstrim, fsync, ftpd, grep, groups, gunzip, gzip, hdparm, head, hexdump,
        hostname, httpd, hwclock, id, ifconfig, ifplugd, insmod, install, iostat, ip, ipcrm, ipcs, kill, killall, killall5, klogd, less, ln, logger, logname, losetup, ls, lsattr, lsmod,
        lsof, lspci, lsusb, lzop, lzopcat, makemime, man, md5sum, mkdir, mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.vfat, mknod, mkswap, modinfo, modprobe, mount, mpstat, mv, nbd-client, nc,
        netstat, nice, nmeter, nohup, ntpd, od, openvt, patch, pidof, ping, ping6, pivot_root, pmap, popmaildir, powertop, printf, ps, pstree, pwd, pwdx, rdate, rdev, readlink, realpath,
        reformime, renice, reset, resize, rev, rm, rmdir, rmmod, route, script, scriptreplay, sed, seq, setfont, setserial, sh, sha1sum, sha256sum, sha3sum, sha512sum, showkey, shuf,
        sleep, smemcap, sort, start-stop-daemon, stat, strings, stty, swapoff, swapon, sync, sysctl, syslogd, tail, tar, tee, test, time, timeout, top, touch, tr, true, tty, tunctl,
        udhcpd, umount, uname, uncompress, uniq, unix2dos, unlink, unlzop, unxz, unzip, uptime, users, usleep, uudecode, uuencode, vi, volname, wall, watch, wc, which, who, whoami, whois,
        xargs, xz, xzcat, yes, zcat
```
ARMv7 (buildroot-armeabi-ng) and ARMv5 (buildroot-armv5eabi-ng) feeds updated.
Please upgrade, test and report back

**Comment by pwallner** [comment]
Thank you, busybox is running now...

    root@mcpatric:/opt/simplebuild# /opt/bin/busybox
    BusyBox v1.23.0 (2015-09-12 13:21:42 EEST) multi-call binary.
    BusyBox is copyrighted by many authors between 1998-2012.
    Licensed under GPLv2. See source distribution for detailed
    copyright notices.

    Usage: busybox [function [arguments]...]
     or: busybox --list
     or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

    Currently defined functions:
        [, [[, acpid, arp, arping, ash, awk, base64, basename, bash, beep,
        blkid, blockdev, bootchartd, bunzip2, bzcat, bzip2, cal, cat, chattr,
        chgrp, chmod, chown, chroot, chrt, chvt, cksum, clear, cmp, comm,
        conspy, cp, cpio, cut, date, dd, deallocvt, depmod, devmem, df,
        dhcprelay, diff, dirname, dmesg, dnsdomainname, dos2unix, du,
        dumpleases, echo, ed, egrep, eject, env, ether-wake, expr, false,
        fatattr, fbsplash, fdisk, fgconsole, fgrep, find, flock, free, fsck,
        fstrim, fsync, ftpd, grep, groups, gunzip, gzip, hdparm, head, hexdump,
        hostname, httpd, hwclock, id, ifconfig, ifplugd, insmod, install,
        iostat, ip, ipcrm, ipcs, kill, killall, killall5, klogd, less, ln,
        logger, logname, losetup, ls, lsattr, lsmod, lsof, lspci, lsusb, lzop,
        lzopcat, makemime, man, md5sum, mkdir, mkdosfs, mke2fs, mkfifo,
        mkfs.ext2, mkfs.vfat, mknod, mkswap, modinfo, modprobe, mount, mpstat,
        mv, nbd-client, nc, netstat, nice, nmeter, nohup, ntpd, od, openvt,
        patch, pidof, ping, ping6, pivot_root, pmap, popmaildir, powertop,
        printf, ps, pstree, pwd, pwdx, rdate, rdev, readlink, realpath,
        reformime, renice, reset, resize, rev, rm, rmdir, rmmod, route, script,
        scriptreplay, sed, seq, setfont, setserial, sh, sha1sum, sha256sum,
        sha3sum, sha512sum, showkey, shuf, sleep, smemcap, sort,
        start-stop-daemon, stat, strings, stty, swapoff, swapon, sync, sysctl,
        syslogd, tail, tar, tee, test, time, timeout, top, touch, tr, true,
        tty, tunctl, udhcpd, umount, uname, uncompress, uniq, unix2dos, unlink,
        unlzop, unxz, unzip, uptime, users, usleep, uudecode, uuencode, vi,
        volname, wall, watch, wc, which, who, whoami, whois, xargs, xz, xzcat,
        yes, zcat

**Comment by alllexx88** [comment]
Great. Closing issue...
