### ISSUE TITLE
rrdtool is missing libart dependency

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#69]
arch i686

$ rrdtool
rrdtool: error while loading shared libraries: libart_lgpl_2.so.2: cannot open shared object file: No such file or directory

$ ipkg install libart
Reinstalling libart (2.3.17-2) on root...
Downloading http://optware-ng.zyxmon.org/buildroot-i686/libart_2.3.17-2_i686.ipk
Configuring libart
Successfully terminated.

$ rrdtool
RRDtool 1.2.30  Copyright 1997-2008 by Tobias Oetiker <tobi@oetiker.ch>
...

also, the perl module doesn't work

$ perl -MRRD
Can't locate RRD.pm in @INC (you may need to install the RRD module) (@INC contains: /opt/lib/perl5/site_perl/5.20.1/i686-linux /opt/lib/perl5/site_perl/5.20.1 /opt/lib/perl5/5.20.1/i686-linux /opt/lib/perl5/5.20.1 .).
BEGIN failed--compilation aborted.

maybe because of this, shoud be /opt/lib/ld-linux.so.2

$ ldd /opt/lib/perl5/site_perl/5.20.1/i686-linux/auto/RRDs/RRDs.so
        linux-gate.so.1 =>  (0xf772f000)
        librrd.so.2 => /opt/lib/librrd.so.2 (0xf76d5000)
        libm.so.6 => /opt/lib/libm.so.6 (0xf7688000)
        libpng12.so.0 => /opt/lib/libpng12.so.0 (0xf765d000)
        libz.so.1 => /opt/lib/libz.so.1 (0xf7643000)
        libfreetype.so.6 => /opt/lib/libfreetype.so.6 (0xf75aa000)
        libc.so.6 => /opt/lib/libc.so.6 (0xf73f7000)
        libart_lgpl_2.so.2 => /opt/lib/libart_lgpl_2.so.2 (0xf73dd000)
        **/lib/ld-linux.so.2 (0xf7730000)**
        libbz2.so.1.0 => /opt/lib/libbz2.so.1.0 (0xf73cc000)

**Comment by alllexx88** [comment]
rrdtool libart dependency is OK:

```
DiskStation> cat /opt/lib/ipkg/info/rrdtool.control
Package: rrdtool
Architecture: i686
Priority: optional
Section: misc
Version: 1.2.30-1
Maintainer: NSLU2 Linux <nslu2-linux@yahoogroups.com>
Source: http://oss.oetiker.ch/rrdtool/pub//rrdtool-1.2.30.tar.gz
Description: Round-Robin Database tool. Database collator and plotter
Depends: glibc-opt, zlib, libpng, freetype, libart
Suggests:
Conflicts:
```

Also, rrdtool doesn't provide RRD perl module, but RRDp and RRDs modules instead:

```
DiskStation> ipkg files rrdtool|grep pm
/opt/lib/perl5/site_perl/5.20.1/RRDp.pm
/opt/lib/perl5/site_perl/5.20.1/i686-linux/RRDs.pm
```
