### ISSUE TITLE
sysfsutils builds right

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#71]
arch i686

$ uname -a
Linux synology 3.10.35 #5644 SMP Tue Dec 1 17:27:54 CST 2015 x86_64 GNU/Linux synology_cedarview_1812+

$ echo $OPTWARE_TOP $OPTWARE_TARGET
/root/git/Optware-ng buildroot-i686

$ cat checksums/sysfsutils-2.1.0.tar.gz.sha512
485902d98b41a69343cb037883d0c0a1de8a1a4aed657cd4528fe10bc845ac51629657dff01deef042e57c9bd9243095e23fc931d06d74db31b03c5f0a18cf07

$ make packages PACKAGES=sysfsutils
...

$ ipkg install packages/sysfsutils_2.1.0-1_i686.ipk
Installing sysfsutils (2.1.0-1) to root...
Configuring sysfsutils
Successfully terminated.

$ /opt/bin/systool -h
Usage: systool [<options> [device]]
        -a                      Show attributes
        -b <bus_name>           Show a specific bus
        -c <class_name>         Show a specific class
        -d                      Show only devices
        -h                      Show usage
        -m <module_name>        Show a specific module
        -p                      Show path to device/driver
        -v                      Show all attributes with values
        -A <attribute_name>     Show attribute value
        -D                      Show only drivers
        -P                      Show device's parent

**Comment by alllexx88** [comment]
Binaries uploaded. Please test

**Comment by gits68** [comment]
well done  thanks :)
