### ISSUE TITLE
lm-sensors builds right

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#72]
arch i686

$ uname -a
Linux synology 3.10.35 #5644 SMP Tue Dec 1 17:27:54 CST 2015 x86_64 GNU/Linux synology_cedarview_1812+

$ echo $OPTWARE_TOP $OPTWARE_TARGET
/root/git/Optware-ng buildroot-i686

$ echo de03332c9e73f90b1fe887174adf1c1f78869922b2fa91beb4625627b79ddbcb9d868ad14e92f6ebba2394092404c7d475cef24e15e83472ece65bbca271f446 > checksums/lm_sensors-3.3.0.tar.bz2.sha512

$ make packages PACKAGES=lm-sensors

$ ipkg install packages/lm-sensors_3.3.0-1_i686.ipk
Installing lm-sensors (3.3.0-1) to root...
Configuring lm-sensors
Successfully terminated.

$ /opt/bin/sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +54.0°C  (crit = +100.0°C)
Core 1:       +55.0°C  (crit = +100.0°C)

but

$ **/opt/sbin/sensors-detect**
**Segmentation fault (core dumped)**

$ ldd /opt/sbin/sensors-detect
        not a dynamic executable

also

$ /opt/sbin/fancontrol
Loading configuration from **/etc/fancontrol** ...
Error: Can't read configuration file

should be **/opt/etc/fancontrol**

**Comment by alllexx88** [comment]
Binaries uploaded, please test

**Comment by gits68** [comment]
well done, thanks :)

**Comment by reDDevil77** [comment]
Sorry, but I don't understand what to do to make sensors-detect and fancontrol working. Can you explain? What "Binaries uploaded" means?

**Comment by gits68** [comment]
it means that the repository have been updated with a working binary package.
```
# ipkg list lm-sensors
lm-sensors - 3.3.0-2 - Linux hardware monitoring.
```
```
# /opt/sbin/sensors-detect
No i2c device files found.
```
=> no more crash (segmentation fault)
```
# /opt/sbin/fancontrol
Loading configuration from /opt/etc/fancontrol ...
Error: Can't read configuration file
```
=> looks in the right directory in /opt/etc and no in /etc
