### ISSUE TITLE
scripts uses a wrong shell

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#74]
arch i686

**well, this issue may be closed since $LD_LIBRARY_PATH seems not to be require anymore since RPATH is rigth set to /opt/lib**

for example, yacc crash

$ yacc
**Segmentation fault (core dumped)**

$ file yacc
yacc: POSIX shell script, ASCII text executable

$ cat /opt/bin/yacc
**#! /bin/sh**
exec '/opt/bin/bison' -y "$@"

should be **#! /opt/bin/sh** because of **$LD_LIBRARY_PATH** may be pointing to /opt/lib which makes /bin/sh crash

$ echo $LD_LIBRARY_PATH
:/opt/lib:/opt/local/lib

so, make/bison.mk could be updated like this at line 181 \:

cp $(BISON_BUILD_DIR)/src/yacc $(BISON_IPK_DIR)$(TARGET_PREFIX)/bin/yacc
**sed -i 's| /bin/sh|/opt/bin/sh|' $(BISON_IPK_DIR)$(TARGET_PREFIX)/bin/yacc**

**Comment by alllexx88** [comment]
Setting `LD_LIBRARY_PATH` is indeed unneeded for Optware-ng. You probably have `/opt/etc/profile` from older `bash` version, which set `LD_LIBRARY_PATH` to `$LD_LIBRARY_PATH:/opt/lib`, but in current version this line was removed.
