### ISSUE TITLE
Can requst new package 6relayd?

### ISSUE THREAD

**Issue by 275761919** [Optware/Optware-ng#80]
I think the 6relayd is better than odhcpd!

**Comment by alllexx88** [comment]
6relayd package added, but it's missing default config and rc script yet. If you're willing to add these, contribution is welcomed

**Comment by 275761919** [comment]
Thank you! I'm realy appreicate your effort for this project!  The source code of the 6relayd of the openwrt'AA should contain the entire “Makefile”, but unluckily, it is unavailable!　I just write a simplest rc script with referring to the rc script of the Transmission!

**Comment by alllexx88** [comment]
I'd appreciate it if you could create a pull request with a config and an rc script, since I'm not familiar with using 6relayd
