### ISSUE TITLE
Package Request :- Squeezelite

### ISSUE THREAD

**Issue by Jernau99** [Optware/Optware-ng#81]
Any chance I could request the package Squeezelite for Optware-NG? Would really appreciate this as I see there is a package for entware but not Optware-NG and I have managed to get a USB soundcard working on my Router under Asus-WRT Merlin and would really like to use the squeezelite player

Many Thanks

**Comment by alllexx88** [comment]
Done. Please test: it fails with 'no output device' on me, since I don't have a usb soundcard
