### ISSUE TITLE
Cannot launch Midnight Commander

### ISSUE THREAD

**Issue by sube74** [Optware/Optware-ng#85]
I have just updated my QNAP TS-221 to Optware-ng using following command:
wget -O - http://ipkg.nslu2-linux.org/optware-ng/bootstrap/buildroot-armv5eabi-ng-bootstrap.sh | sh

Now my Midnight Commander is not working, I get following error:
/share/MD0_DATA/.qpkg/Optware/bin/mc: can't load library 'libintl.so.8'

Running the strace command I get the following:
[/opt/etc] # strace mc
execve("/opt/bin/mc", ["mc"], [/* 26 vars */]) = 0
readlinkat(AT_FDCWD, "/proc/self/exe", "/share/MD0_DATA/.qpkg/Optware/bi"..., 4096) = 36
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x76fe2000
open("/opt/lib/libslang.so.2", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=807520, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x76fe1000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0p\352\1\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 1126400, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76ebb000
mmap2(0x76ebb000, 741432, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x76ebb000
mmap2(0x76f80000, 64888, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xb5000) = 0x76f80000
mmap2(0x76f90000, 252796, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x76f90000
close(3)                                = 0
munmap(0x76fe1000, 4096)                = 0
open("/opt/lib/libglib-2.0.so.0", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=842160, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_UNINITIALIZED, -1, 0) = 0x76fe1000
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\220\357\0\0004\0\0\0"..., 4096) = 4096
mmap2(NULL, 872448, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76de6000
mmap2(0x76de6000, 835488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x76de6000
mmap2(0x76eba000, 1656, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xcc000) = 0x76eba000
close(3)                                = 0
munmap(0x76fe1000, 4096)                = 0
open("/opt/lib/libintl.so.8", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/lib/libintl.so.8", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/lib/libintl.so.8", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/lib/libintl.so.8", O_RDONLY)     = -1 ENOENT (No such file or directory)
open("/usr/lib/libintl.so.8", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/X11R6/lib/libintl.so.8", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/lib/libintl.so.8", O_RDONLY) = -1 ENOENT (No such file or directory)
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76fe1000
write(2, "", 0)                         = 0
write(2, "/share/MD0_DATA/.qpkg/Optware/bi"..., 36/share/MD0_DATA/.qpkg/Optware/bin/mc) = 36
write(2, ": can't load library '", 22: can't load library ')  = 22
write(2, "libintl.so.8", 12libintl.so.8)            = 12
write(2, "'\n", 2'
)                      = 2
munmap(0x76fe1000, 4096)                = 0
exit(16)                                = ?
+++ exited with 16 +++
[/opt/etc] #

I have no clue on how to continue.

Thanks,
Sune

**Comment by alllexx88** [comment]
Looks like mc is missing `gettext` dependency. Fixed, it's being rebuilt now. Wait till feeds are updated, or just install gettext manually:

```
ipkg install gettext
```

**Comment by sube74** [comment]
I have just tried to install gettext, but somehow I cant install it. I get the following:
[~] # ipkg install gettext
Installing gettext (0.19.6-1) to /opt/...
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng/gettext_0.19.6-1_arm.ipk
Installing libiconv (1.13.1-1) to /opt/...
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armv5eabi-ng/libiconv_1.13.1-1_arm.ipk
An error ocurred, return value: 2.
Collected errors:
Package libiconv wants to install file /opt/include/iconv.h
        But that file is already provided by package libc-dev
Package libiconv wants to install file /opt/bin/iconv
        But that file is already provided by package gconv-modules


/Sune

**Comment by sube74** [comment]
I now got gettext installed with -force-overwrite, rebooted and now Midnight Commander is working.
Thanks
/Sune
