### ISSUE TITLE
autoconf and co

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#89]
Hi,

**about autoconf**

$ automake --add-missing
sh: /home/alex/optware/buildroot-i686/host/staging/opt/bin/autoconf: not found
automake: error: /home/alex/optware/buildroot-i686/host/staging/opt/bin/autoconf failed with exit status: 127

$ type automake
automake is hashed (/opt/bin/automake)

$ grep alex /opt/bin/automake
  my $traces = ($ENV{AUTOCONF} || '/home/alex/optware/buildroot-i686/host/staging/opt/bin/autoconf') . " ";

$ sed -i -e 's|/home/alex/optware/buildroot-i686/host/staging||' /opt/bin/automake

$ automake --add-missing
configure.ac:12: installing 'conf/compile'
configure.ac:8: installing 'conf/missing'
libopkg/Makefile.am: installing 'conf/depcomp'

**here is and co**

$ grep /home/alex.*bin/i686 * | grep -v Binary | tr ' ' '\n' | egrep 'i686-buildroot|staging' | tr -d "\"'" | sed 's|.*[=,]||;s|-[IL]||;\|^[^/]|d' | sort -u
/home/alex/optware/buildroot-i686/staging
/home/alex/optware/buildroot-i686/staging/opt/include
/home/alex/optware/buildroot-i686/staging/opt/lib
/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-ar
/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-as
/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-g++
/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-gcc
/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-ld
/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-nm
/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-ranlib
/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-strip

$ egrep '/home/alex.*bin/i686|i686/staging' * | grep -v Binary | sed 's|:.*||' | sort -u
automake-1.15
curl-config
freetype-config
gdlib-config
icu-config
libgcrypt-config
**libtool**
neon-config
net-snmp-config
net-snmp-create-v3-user
xft-config
a simple sed may be used to get rid stagind and build directories : 

$ sed -i -e 's|/home/alex/optware/buildroot-i686/staging/|/|' \
-e 's|/home/alex/optware/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.2.0/bin/i686-buildroot-linux-gnu-|/opt/bin/|' ...

well, this left "/home/alex/optware/buildroot-i686/staging" used by --with-ssl in curl-config
I suppose this may be replaced by /opt

**Comment by bolkedebruin** [comment]
+1, see the same issue here.

**Comment by alllexx88** [comment]
I believe this is finally fixed, and will become online soon. It was troublesome, and so being continiuously pushed down the to-do list, but finally done. Thanks for the report, and sorry for the delay :smiley:
