### ISSUE TITLE
Wget-SSL segmentation fault

### ISSUE THREAD

**Issue by tleepa** [Optware/Optware-ng#90]
Hi,

I have tried to use the optware-ng on my Asus RT-AC56U router ( uname -a: Linux rtr 2.6.36.4brcmarm #3 SMP PREEMPT Thu Oct 8 20:55:52 CEST 2015 armv7l GNU/Linux).
The wget-ssl package has installed with its dependencies, but it segfaults on run.
Please find attached files for additional details (strace log and ldd info).

Regards,
Tomasz
[wget-ssl_ldd.txt](https://github.com/Optware/Optware-ng/files/163340/wget-ssl_ldd.txt)
[wget-ssl_strace.txt](https://github.com/Optware/Optware-ng/files/163341/wget-ssl_strace.txt)

**Comment by alllexx88** [comment]
Hi,

How did you bootstrap Optware-ng? What feed you use? The ldd output is totally wrong, and differs from my output:

```
root@unknown:/opt# ldd /opt/bin/wget
        libiconv.so.2 => /opt/lib/libiconv.so.2 (0x4018f000)
        libpcre.so.1 => /opt/lib/libpcre.so.1 (0x4010e000)
        libuuid.so.1 => /opt/lib/libuuid.so.1 (0x40140000)
        libnettle.so.4 => /opt/lib/libnettle.so.4 (0x400a8000)
        libgnutls.so.28 => /opt/lib/libgnutls.so.28 (0x4027c000)
        libz.so.1 => /opt/lib/libz.so.1 (0x40153000)
        libidn.so.11 => /opt/lib/libidn.so.11 (0x40370000)
        libc.so.1 => /opt/lib/libc.so.1 (0x403b0000)
        libstdc++.so.6 => /opt/lib/libstdc++.so.6 (0x4045c000)
        libm.so.1 => /opt/lib/libm.so.1 (0x40559000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x4057a000)
        ld-uClibc.so.1 => /opt/lib/ld-uClibc.so.1 (0x400f7000)
        libtasn1.so.6 => /opt/lib/libtasn1.so.6 (0x405a7000)
        libhogweed.so.2 => /opt/lib/libhogweed.so.2 (0x405c5000)
        libgmp.so.10 => /opt/lib/libgmp.so.10 (0x405fc000)
```

And it works for me:

```
root@unknown:/opt# /opt/bin/wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

Also, I see from strace that it looks in '/lib', '/usr/lib', etc., which it should not do if correct dynamic loader is used. Though I see from strace log that it stats /opt/lib/ld-uClibc.so.1, it never opens it, and opens /lib/ld-uClibc.so.0 instead, thus leading to incorrect behaviour. I can only guess that your Optware-ng setup is terribly wrong, please try to make a clean bootstrap.

Regards,
Alex

**Comment by tleepa** [comment]
Hi,

I have made this: `http://ipkg.nslu2-linux.org/optware-ng/bootstrap/buildroot-armeabi-ng-bootstrap.sh` to bootstrap and `http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng` feed.

How did I bootstrap?
I made the /opt empty and run the command:
`wget -O - http://ipkg.nslu2-linux.org/optware-ng/bootstrap/buildroot-armeabi-ng-bootstrap.sh | sh`
I did not reboot the router, though - is that necessary?

What you wrote about the libraries made me look at my LD_LIBRARY variable and it was set to `'/lib:/usr/lib:/usr/local/lib:/opt/lib:/opt/usr/lib'`. I have changed it, so the two /opt paths are at the front, but then I am getting the following error while running number of commands (Tomato built-in wget, find, etc.):
`/bin/sh: '/opt/lib/libc.so.1' library contains unsupported TLS
/bin/sh: can't load library 'libc.so.1'`
FYI my PATH variable is set to `'/opt/usr/sbin:/opt/sbin:/opt/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin'`.

**Comment by alllexx88** [comment]
>  LD_LIBRARY variable and it was set to '/lib:/usr/lib:/usr/local/lib:/opt/lib:/opt/usr/lib'

That's the culprit! Please unset this variable -- Optware-ng doesn't need it. Setting `/opt/lib` first will break firmware apps, and `/lib:/usr/lib` at front will break Optware-ng. Just empty it, and it should be fine.

**Comment by tleepa** [comment]
Indeed, it is working fine after the change!

Thank you very much for your help :)
