### ISSUE TITLE
usbutils / usb.ids

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#92]
Hi,

/opt/share/misc/usb.ids isn't up to date, 
**/opt/sbin/update-usbids.sh** have to be run at postinstall time.

**before**
$ lsusb -tv
Bus#  8
`-Dev#   1 Vendor 0x1d6b Product 0x0003
  `-Dev#   4 Vendor 0x152d Product 0x0551

$ /opt/sbin/update-usbids.sh
--2016-03-09 00:04:43--  http://www.linux-usb.org/usb.ids
Resolving www.linux-usb.org (www.linux-usb.org)... 216.34.181.97
Connecting to www.linux-usb.org (www.linux-usb.org)|216.34.181.97|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 560164 (547K) [text/plain]
Saving to: '/opt/share/misc/usb.ids.new'

/opt/share/misc/usb. 100%[========================>] 547.04K   346KB/s   in 1.6s

2016-03-09 00:04:45 (346 KB/s) - '/opt/share/misc/usb.ids.new' saved [560164/560164]

Done.

**after**
$ lsusb
Bus 008 Device 004: ID 152d:0551 JMicron Technology Corp. / JMicron USA Technology Corp.
...

Regards.

**Comment by alllexx88** [comment]
Fixed: 193b6e8b7cd43813fcaff255749afb630cde7deb
