### ISSUE TITLE
node js 4.3.1

### ISSUE THREAD

**Issue by uronito** [Optware/Optware-ng#97]
Allexx88 can you compile nodejs for optware or entware please?

i would like run homebridge in my ac87u.

Thanks!!!!!!

**Comment by alllexx88** [comment]
I'll look into it adding it to Optware-ng, but no promises. OpenWRT, on which Entware-ng is based, has an old version of it -- 0.12.7. Current LTS, btw, is 4.4.0 -- why would you want 4.3.1 exectly?

**Comment by cswl** [comment]
I think this could be just compiled with prefix in configure.
As, using a wrapper on the distributed tarball from nodejs.org seems to be working. 

```
LD_LIBRARY_PATH=/opt/lib /opt/lib/ld-linux-armhf.so.3  /opt/local/nodejs/bin/node  --version
5.9.0
```

**Comment by alllexx88** [comment]
@cswl this will not work for uclibc-ng targets, since uclibc-ng isn't compatible with glibc, and ac-87u doesn't have an FPU, and thus uses buildroot-armeabi-ng feed, which is a uclibc-ng target. I'll look into adding nodejs sometime soon. If it's feasible, maybe I'll do it today

**Comment by alllexx88** [comment]
@uronito v4.4.1 added: `node` package
