### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by clsalva** [Optware/Optware-ng#98]
I was following the "Contributing to Optware ng" guide, but i had the following error while running

`make directories toolchain ipkg-utils`

> [/opt/Public/Optware-ng/buildroot-armeabihf] # make directories toolchain ipkg-utils
> make: Nothing to be done for 'directories'.
> rm -f /opt/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-armhf-linux-3.2.66-glibc-5.2.0/.built
> make STAGING_DIR=/opt/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-armhf-linux-3.2.66-glibc-5.2.0/arm-buildroot-linux-gnueabihf/sysroot -C /opt/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08
> make[1]: Entering directory '/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08'
> /opt/bin/make -j1  HOSTCC="/opt/bin/gcc" HOSTCXX="/opt/bin/g++" silentoldconfig
> make[2]: Entering directory '/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08'
> BR2_DEFCONFIG='' KCONFIG_AUTOCONFIG=/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08/output/build/buildroot-config/auto.conf KCONFIG_AUTOHEADER=/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08/output/build/buildroot-config/autoconf.h KCONFIG_TRISTATE=/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08/output/build/buildroot-config/tristate.config BR2_CONFIG=/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08/.config BR2_EXTERNAL=support/dummy-external SKIP_LEGACY= /share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08/output/build/buildroot-config/conf --silentoldconfig Config.in
> /bin/sh: /share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08/output/build/buildroot-config/conf: No such file or directory
> Makefile:778: recipe for target 'silentoldconfig' failed
> make[2]: *** [silentoldconfig] Error 127
> make[2]: Leaving directory '/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08'
> Makefile:429: recipe for target '/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08/output/build/buildroot-config/auto.conf' failed
> make[1]: *** [/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08/output/build/buildroot-config/auto.conf] Error 2
> make[1]: Leaving directory '/share/CACHEDEV1_DATA/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-2015.08'
> /opt/Public/Optware-ng/platforms/toolchain-buildroot-armeabihf.mk:90: recipe for target '/opt/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-armhf-linux-3.2.66-glibc-5.2.0/.built' failed
> make: *** [/opt/Public/Optware-ng/buildroot-armeabihf/toolchain/buildroot-armhf-linux-3.2.66-glibc-5.2.0/.built] Error 2
> [/opt/Public/Optware-ng/buildroot-armeabihf] #

thanks for help
k.

**Comment by alllexx88** [comment]
`/share/CACHEDEV1_DATA` tells me that you're trying to build Optware-ng on a QNAP device. That won't work -- unless you install normal Linux distro on it. Using Optware-ng build tools is not an option here.

**Comment by clsalva** [comment]
Yes that's what i was trying. I succeeded compiling a program and i wanted to try to build an ipkg for ARMv7 users. Thought i could do that directly on the QNAP architecture.

thanks anyway Alex

**Comment by alllexx88** [comment]
You're welcome. Building on QNAP would be rather slow anyway
