### ISSUE TITLE
Missing perl modules SOAP::Lite, LWP::Simple, LWP::UserAgent, SOAP::Lite HTTP::Request

### ISSUE THREAD

**Issue by GUHU0433** [Optware/Optware-ng#99]
As stated here, it is not advisable to compile CPAN Modules on the target platform. I would like to use my synology Diskstation (armeabihf) for fhem, thus I need the following perl modules:

SOAP::Lite, LWP::Simple,  LWP::UserAgent,  SOAP::Lite HTTP::Request

which don't seem to be included. Could somebody be so kind to include it into the package? I think it would be great for a huge number of users.

Thank you in advance

**Comment by alllexx88** [comment]
@trammel Could you please take a look at this? You've done a great job adding several perl modules, it would be great if you could add these too. I can look into it myself later too -- busy with other things right now

**Comment by trammel** [comment]
SOAP::Lite isn't packaged yet, I'll look at that.
LWP::Simple and LWP::UserAgent are part of the perl-libwww package, which is currently available.
HTTP::Request is part of the perl-http-message package, which @alllexx88 merged early March.

**Comment by alllexx88** [comment]
Thanks to @trammel I think we can close this

**Comment by GUHU0433** [comment]
Thank you both very much for your effort.
